### ISSUE TITLE
Crash on minimal ert configs

### ISSUE THREAD

**Issue by berland** [equinor/ert#1030]
The smallest ert config I am able to get to "work" (*)  is this:

```
ECLBASE 2_R001_REEK-0.DATA
QUEUE_SYSTEM LOCAL
NUM_REALIZATIONS 1
```

If  `QUEUE_SYSTEM` or `ECLBASE` is missing, a long stacktrace `util_abort__()` is printed - this could be improved.

If `NUM_REALIZATIONS` is missing, I get a hint that NUM_REALIZATIONS is missing before `util_abort__()` gives a coredump.

(*) "work" means that `ert test_run foo.ert` runs fine with zero exit status.

**Comment by markusdregi** [comment]
If `QUEUE_SYSTEM` is specified in your site-config then this should run:

```
NUM_REALIZATIONS 1
JOBNAME some_job_name
```

But I guess you were not looking for the smallest ERT configuration possible to run ;)

First, I can say that the interplay between `ECLBASE` and `JOBNAME` is not so transparent. It is stated in the documentation that one of them needs to be specified and for non-Eclipse-like simulator based setups I would recommend using `JOBNAME`...

Second, I guess the real problem here is that the user friendliness of the configuration system of ERT is not as good as we would like it to be. Not with respect to error messages, nor the expressiveness of the configuration. This is why we have currently launched a milestone towards a first version of a new configuration system of ERT (see https://github.com/equinor/ert/issues/1013). Currently the discussion is around an Ensemble Evaluator API that can naturally facilitate evaluating ensembles and then back a first yaml-based configuration allowing for running ensemble experiments (see https://github.com/equinor/ert/issues/1023).

Due to this I'm closing this issue as a **won't fix**. There are numerous problems with the existing configuration system and we are hoping to address them in the future system that we hope to get a first version of out for testing as soon as possible.
