### ISSUE TITLE
Ert config dump in realization directories

### ISSUE THREAD

**Issue by berland** [equinor/ert#113]
I would like a json dump of the entire ert config file in each realization directory, written upon realization initialization (same time as jobs.json is written).

**Comment by pgdr** [comment]
Why?  Due to the refactoring work we did last year, this should be possible, but what kind of information are you looking for?

**Comment by berland** [comment]
Knowing the ert config (and the ert config directory's location) is important for traceability starting only with files in RUNPATH. At some point in time, also a reference to a git hash of the model version.

Automatic report generation (webviz) can benefit from knowing the ert config, presenting it when needed.

When project specific scripts have been used (stored alongside the ert config file), it is difficult to determine from files in RUNPATH where those scripts are located, not knowing the location of the ert config.

**Comment by pgdr** [comment]
My hesitation is mainly that it implies an even harder dependence on the current config format.

We can definitely add the _path to the config file_ into the `jobs.json` as simply
```json
{
"umask" : "0002",
"DATA_ROOT": "/data/egg/everest/model",
"global_environment" : {"..."},
"global_update_path" : {},
"jobList" : "",
"..." : " ",
"ert_version" : [2, 3, "git"],
"run_id" : "18586:38712:2018-7-02-06-28-20:999867137d",
"ert_pid" : "18586",
"config_file" : "/path/to/conf.ert"
}
```

**Comment by berland** [comment]
That is a valid point. I will be happy with the path to the config file in `jobs.json`

**Comment by berland** [comment]
Any updates on this?

**Comment by markusdregi** [comment]
I've discussed this with @eivindsm and our suggestion is to not implement this. The reason is that it creates an odd and unfortunate data ownership model where the runpath knows which config file produced it. Since the configuration dictates the runpath, this should also be the flow to get the connection between the runpath and config. Otherwise, the user is changing the configuration file to produce a different result (in this discussion runpath) and simultaneously invalidates another runpath that now believes that it is the result of a different configuration file then the one that produced it. You can of course create a similar invalid scenario by having a second config file run in the same runpath, but in this scenario it is still the config-files together that dictated behavior and that connects config and runpath.

I would be happy to assist you in programmatically extracting the runpath from an ERT-configuration file; the API already exists. Then you could very easily given an ERT-configuration file, extract the runpath and use fmu-ensemble (or whatever) to load data. This would also be more in line with future flow when ERT's data API is richer and this is the true source of data.

**Comment by berland** [comment]
Thanks for info, closing issue.

(fmu-ensemble can currently load from the ERT_RUNPATH_FILE, but in this issue it is back-tracking from RUNPATH that is the challinging thing)
