### ISSUE TITLE
Adapt Ensemble/Ensemble Evaluator to the outcome of the discussion about stages/steps/jobs 

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1220]
Stages are organizational, i.e they can contain a grouping of other stages and steps to form a logical unit. 
Stages are what users connect together in their config file.

Steps are units of work that have clearly defined inputs and outputs. Steps will come in different types, for example unix steps, python steps. 

Jobs are needed, however some step types might only have one job. 

What we need to change in the current implementation
- Stages can now contain other stages
- There will be **one** top level stage 
- Every time a step updates it's status, then the stage status is updated for all for every stage that includes this step.
- Change events from the queue system to be step events
- Should be able to handle events coming out of order (and possibly not at all)

**Comment by sondreso** [comment]
The update snapshot resulting of this should also be updated such that all items contains a pointer to their parent.

**Comment by sondreso** [comment]
There are three key groups of information that needs to be present in the new version of Snapshots/PartialSnapshots: 

1. A description of the DAG of steps, including the inputs and outputs linking them together. It is not yet decided if this should also contain a description of the jobs inside each step, if this could also be a separate section, or if should be inferred from information from point 3 in this list. 
2. A description of the grouping of steps into stages (and stages inside stages). This will result in a tree-structure.
3. A list of the status of all steps and jobs, for all realisations. This should be an flat datastructure.

Point 1 and 2 only needs to be sent to clients one time, and all status updates after that (called PartialSnapshots today) will only contain updates to the flat list of statuses for steps and jobs. 

The status of a stage is entirely decided from the status of its direct children (be it steps or stages). Whether this is part of the statuses sent to the clients, or this is up to the clients to calculate themselves is not yet decided. 
In addition, we should implement all updates to statuses as state machines, both to catch errors quicker/fail faster, but also to be able to handle events coming out of order. 

This information will make clients capable off displaying the DAG of steps and the status for each part of the ensemble, as well as groupings based on stages. It also allows the clients to be flexible in how and what information they use when rendering an interface. An example is the QT GUI in the current version of ERT, which (with only minor modifications) could discard the DAG information and display a flat list of all the jobs exactly as today.

**Comment by jondequinor** [comment]
Some points from a discussion between me and @sondreso:

- Stages have inputs, so they're not purely organizational, since from a user POV they will have distinct inputs and outputs.
- Stages' IO will be a mapping to and from steps IO within that stage.
- Stages will create a dag, but this will be expressed to e.g. Prefect as a dag of tasks.
- "Linking" of step definitions to steps will have to be introduced to the ert3 config. Same goes (by extension of points above) for stages?
- Complexity of validating more dynamic properties like relationships between steps/stages, could be best put in the DSL.
- How to communicate status and results of an ensemble, from the Ensemble Evaluator, is not carved in stone yet, but we want to find a good way to satisfy
  1. Ease of introspection (i.e. json is nice, protobuf not so nice)
  1. Not bloated, but not requiring a lot of computation either
  1. Logical
