### ISSUE TITLE
Authority on information about evaluations/experiments

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1250]
We need a higher level concept than the ensemble evaluator to control what evaluations are running, and provide information about this to other modules and clients.

In particular, we are running into issues because we are unable to differentiate between the evaluation not having started yet and the evaluation already being done. 

- Phases should be events
- Be stoppable. Today only the queue is allowed to be killed, all parts of the experiments should be cancelable. 
- Support more modes of re-runs/restarts. See https://github.com/equinor/ert/issues/358
- In the same vein as above, implement support for restarting failed runs from the last successful forward model componen as described in https://github.com/equinor/ert/issues/609
- Handle long running jobs

**Comment by markusdregi** [comment]
This is a later in the process, but still kind of related to #1325

**Comment by oysteoh** [comment]
Dealing with sockets and ports, i have a "finding" i can add to this issue.

Due to the evaluator using an instance of the config with `host` / `port` to acquire a socket we need to bind with `reuse_addr` flag. This because the binding could happen multiple times towards the same `port`. Without the flag we could experience flakyness due to the fact we never know how long it will take the server to shut down the socket and make it available for binding again. With `reuse_addr` the socket can be bound to even if it is in `TIME_WAIT` state.
