### ISSUE TITLE
What are blocks in `ministep.get_obs_data()`?

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1276]
When extracting, we are iterating over "blocks" from `ministep.get_obs_data()`. First of all, what are ministeps and is it correct that we're ignoring all but the last one? Second, we are overwriting `active_obs[obs_key]`. Can multiple blocks have the same `obs_key`? In my mind this makes sense based on the name "block". If so, then the following snippet is a bug.

https://github.com/equinor/ert/blob/028f958c789421acd83f82e35002b7450d44d3d1/ert_shared/storage/extraction_api.py#L159-L163

**Comment by sondreso** [comment]
Discussed this with @dotfloat, and the short summary is: 
> First of all, what are ministeps and is it correct that we're ignoring all but the last one?
 
Ministeps are iterations _inside_ of one update step (i.e. some update algorithms can make several steps for each update, not sure if any of the current algorithms does this). The algorithm can activate and deactivate observations for each ministep, but we use the last ministep to determine which observations where active or not. This has obvious weaknesses, but it at least provides the correct answer for algorithms with one ministep. 

> Second, we are overwriting active_obs[obs_key]. Can multiple blocks have the same obs_key? In my mind this makes sense based on the name "block". If so, then the following snippet is a bug.

No multiple blocks can not have the same key. Blocks are a one to one mapping of observations keys to the part of the obs_data "vector" that contains that key. (obs_data holds all observations)

**Comment by joakim-hove** [comment]
This is complicated and there is lot's of history here, but I think you are summarizing/attacking this from a slightly wrong angle:

**obs_data / obs_block : it is a temporary datastructure**

The observations are managed by several different datatypes, these datatypes are opaque and can not be meaningfully compared or be subject to mathematical operations in their representation. When doing the actual update the observations should enter into the equations as matrices `R` and `d_obs`; however some normalization  and filtering and so on must be performed before the observation data enters the final matrices `R` and `d_obs` - this is the role of `obs_data / obs_block`.

Assuming you ave a setup with two observations: 
```
SUMMARY_OBSERVATION WGOR_2018
{
    VALUE = 8;
    ERROR = 2;
    RESTART = 37;
    KEY = WGOR:PROD;
};

GENERAL_OBSERVATION GEN_OBS10 {
    DATA = DATA;
    RESTART = 10;
    OBS_FILE = "gen_obs_data";
};
```

Then the data flow will be as such:

1. The data starts with one `gen_obs_type` and one `summary_obs_type` which is the "real observation data" - with metadata and all.
2. During the update process a temporary `obs_data` structure will be created, the `obs_data`structure will consist of two `obs_block` instances - one for the data from the `WGOR_2018` observation and one block from the `GEN_OBS10` observation.
3. Outliers and points with two small variation (actually "the same") are filtered out from `obs_data` and matrices are created. 

Assuming the `GEN_OBS10` has three elements the `obs_data` structure can look like this:
```
                    [[  125     67    ]   WGOR_2018 -> first obs_block
                     [  3.56   1.20
obs_data =              4.20   1.45       GEN_OBS10 -> second obs_block
                        4.07   1.30 ]]
```  

The òbs_data` structure will resemble a `N x 2` matrix, with measurmement values in the first column and standard deviation values in the second column.

So - all in all I see obs_data / obs_block as ephemeral datastructures and wonder whether it is sound to represent them in a storage api.


**Updatestep / ministep / .... - local updates**
The `obs_data` structure described above applies to one update (as in one call to the linear algebra routines) and is totally independent of the local update configuration - the local update configuration has been applied *before* the `obs_data` structure is assembled.

Originally the smoother update would update *all parameters* and use *all observations* in the process. Then at a later stage the concept of local updates was introduced. The purpose of local updates was to enable an update configuration where subsets of parameters and observations were grouped together - so that only some of the observations would provide data for updating some of the parameters. This is further complicated by the possibility to update only parts of a parameter based on a set of active indices, and in the same way only a part of an observation can be used.

The local configuration has three principle layers. 

**local_updatestep_type:** This is the top level type; in current ert can only be one `local_updatestep` instance. Having a separate `local_updatestep_type`is a historical remnant from the EnKF algorithm where it was possible to configure different local configurations for different timesteps - now only smoother algorithms are relevant and the time direction is moot.

**local_ministep_type:** The updatestep can consist of several ministeps - each ministep is defined by the observations (i.e. obs_keys and indices) in the ministep - and in most cases the linear algebra (i.e. determine X matrix) can be done once for the entire ministep.

**local_dataset_type:** Each ministep can consist of several `local_dataset_type` - one `local_dataset_type` is a collection of parameters which should be updated in the same way.

The configuration of local updates is way too complex; in addition to the complexity which originates in the per-timestep configuration of the EnKF era it was a principle that the various sets of parameters should be named - so that e.g. the same set of parameters could be easily configured to be updated with two different observations sets. 

Good luck :-)

**Comment by markusdregi** [comment]
Thanks for the really nice explanation @joakim-hove! 👏🏻 Closing the issue due to inactivity.
