### ISSUE TITLE
Finding open port needs to be done as close to server startup as possible

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1358]
Currently the port is resolved when the config is first imported, which is way too early. To reproduce: Open two ERT instances and hit run at approximately the same time. 

https://github.com/equinor/ert/blob/1897964956728c81606ebd994c7776897addcf62/ert_shared/ensemble_evaluator/config.py#L31

**Comment by dotfloat** [comment]
ERT Storage entirely eliminates this race condition by handing the socket off to uvicorn directly. You should be able to do the same with `websockets.serve([..], sock=my_existing_socket)` since `websockets` v3 in 2017

ERT Storage: https://github.com/equinor/ert/blob/1897964956728c81606ebd994c7776897addcf62/ert_shared/storage/main.py#L106

I open a socket and then pass it to `uvicorn`, which then uses it instead of opening any new ones. Race condition no more!
