### ISSUE TITLE
Introduce experiment concept into storage

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1406]
`ert3` comes with an experiment concept, storage should be able to represent records.

Definition should be agreed upon up front in https://github.com/equinor/ert/issues/1404

**Comment by dotfloat** [comment]
We haven't had a discussion on this yet. Here are my preliminary thoughts:

An experiment encapsulates the concept of the user's full configuration. The main thing that an experiment contains is `ensemble` or "ensemble run", "ensemble evaluation". Thus, the `experiment` table is something that a lot of other tables will refer to.

# Table
```
experiment {
  id: int
  workspace_id: int

  observation: List[Observation]
  ensemble: List[Ensemble]
  prior: List[Prior]

  time_created: Timestamp   # When this DB entry was created 
  time_updated: Timestamp   # When this DB entry was updated (metadata column is mutable, so it makes sense)
  metadata: Optional[JSON]  # https://github.com/equinor/ert/issues/1383
}
```
`Optional[T]` means the column is type `T`, and is `NULL`able.

Here, the `experiment` table itself is really empty. It doesn't even have a name. We instead change all the other tables that store configuration data that exists prior to an ensemble run.

And ensemble run, or `ensemble`, both points to an `experiment` entry (configuration), and optionally to a previous `ensemble` via the `update` table (algorithm, eg. ES-MDA). This means that an `ensemble` is using a new configuration, but is continuing from a `ensemble` that ran in a previous configuration. This allows the user to run two iterations, manually change their observations, then continue for one more iteration.

# Endpoints
These are generic resource-based endpoints
* `GET /experiments`
  List all experiments for the workspace
* `POST /experiments`
  Initialize a new experiment
* `GET /experiments/{ensemble_id}`
  Get a particular experiment by ID

# JSON Initialisation
We might want upload the entire configuration all at once. As such, this JSON could be big. We want this because we want to keep a consistent database. That is, both the prior and posterior state of the database is valid. We don't want a partially-initialised resource.

```py
class ExperimentCreate(pydantic.BaseModel):
    observations: List[ObservationCreate]
    priors: List[PriorCreate]
    response_definition_observation_link: Mapping[str, str]  # POLY_RES <--> POLY_OBS link
```
I don't feel strongly about this and such a solution could get messy really quick. However, I do believe we should keep database consistency at a high priority, and so this should be solved somehow. Eg, we could consider uploading multipart form-data, as supported by the HTTP standard. The first part of this data could be a JSON file, which refers to the other parts by some token in the JSON.

Alternatively, we could also send multipart form-data, where each part is a separate configuration object. Eg, the first two "files" are observations, followed by fifteen priors. It seems like each file can have its own HTTP headers, so we could end up storing the type of data (one of `observation`, `prior`, etc), we could start uploading resources in more efficient formats.

FastAPI on Multiple File Uploads: https://fastapi.tiangolo.com/tutorial/request-files/#multiple-file-uploads

**Comment by oysteoh** [comment]
Duplicated by equinor/ert-storage#21
