### ISSUE TITLE
Introduce record concept into storage

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1407]
`ert3` comes with an experiment concept, storage should be able to represent records.

Definition should be agreed upon up front in https://github.com/equinor/ert/issues/1404

**Comment by dotfloat** [comment]
We had a ~~long and arduous conversation~~ short comment.

# Table

```
file {
  id: int
  ensemble_id: int
  realization_index: int    # 0 - <number of realizations in ensemble>

  name: str                 # Unique for (ensemble_id, realization_index)
  mimetype: str             # The Mimetype of the uploaded record

  data_ext: Optional[int]   # Some key for the external BLOB store (Won't Implement Yet)
  data_int: Optional[BLOB]  # Internal RDBMS blob
  data_size: int            # Data size in number of bytes

  created_by: Stage         # (Won't Implement Yet)
  used_by: List[Stage]      # (Won't Implement Yet)

  time_created: Timestamp   # When this DB entry was created 
  time_updated: Timestamp   # When this DB entry was updated (metadata column is mutable, so it makes sense)
  metadata: Optional[JSON]  # https://github.com/equinor/ert/issues/1383
}
```

`Optional[T]` means the column is type `T`, and is `NULL`able.

`data_ext` won't be implemented until we're on Azure. The idea is that for really small payloads, we don't want to have to access the blob store. When a file is uploaded, the server will make the decision whether to send it to the blob store or to keep it in the RDBMS. The threshold could be like 100 bytes, we'll see. One of `data_ext` or `data_int` must be set (XOR). When requesting the record data, if `data_int` is not-NULL, return it. If `data_ext` is not-NULL, access the BLOB store with the key.

`data_size` exists so we can return metadata about the record without having to query the BLOB store about the size.

Stages aren't well-defined concepts in storage yet, but we might want to figure out whether who created it and who consumed it. Maybe this'll be obtainable in a different way, or maybe a stage could programmatically get/put records.

The timestamps and metadata are nice to have, but not required. Metadata will allow for easier prototyping as we won't need to add columns to the database, but is ultimately meant for the users only. Ie, ERT(3) should not make any decisions based on the contents of the metadata, only for proof-of-concept work.

# Endpoints
* `GET /ensembles/{ensemble_id}/records`
  Get a list of _all_ record metadata.
* `GET /ensembles/{ensemble_id}/records/{name:str}/{realization_index}`:
  JSON metadata (not only `metadata` column, but all metadata for the record)
* `HEAD /ensembles/{ensemble_id}/records/{name:str}/{realization_index}/data`:
  HTTP-compatible metadata (Headers-only). Eg, name, size, mimetype, cache info, etc
* `GET /ensembles/{ensemble_id}/records/{name:str}/{realization_index}/data`:
  Get contents of record also. Same header information as above
* `POST /ensembles/{ensemble_id}/record/{name:str}/{realization_index}`:
  Use standard HTTP file uploading stuff to create a new record.

**Metadata endpoints**
Optional, see: https://github.com/equinor/ert/issues/1383

# Sample JSON
The metadata `GET`s will return something like:
```json
{
  "id": 0,
  "ensemble_id": 1,
  "realization_index": 2,
  "name": "coefficients",
  "mimetype": "text/csv",
  "data_size": 3,
  "time_created": "2020-01-02T03:04:05Z",
  "time_updated": "2021-02-03T14:15:16Z",
  "_meta": {
    "foo": "bar"
  }
}
```
The `_meta` field is the user-specified metadata and can be safely ignored.

# Client Usage
The client can use the `requests` library to get and post data. Getting data should be straightforward, eg:
```python
r = requests.get(f"/ensembles/{ensemble_id}/records/{name}/{index}/data", stream=True)
df = pandas.from_csv(r)
```
Posting data should also be relatively simple
```python
with open("coefficients.json", "rb") as f:
  requests.post(
    f"/ensembles/{ensemble_id}/records/{name}/{index}",
    stream=True,
    data=f,
    headers={"Content-Type": "text/csv"}
  )
```

The specifics will differ. The current storage connection helper code isn't very good.

# ERT3-specific notes
Since ERT3 doesn't have a concept of "ensemble runs" yet (?), nor does it have the ability to post the initial ensemble data, we'll ignore the `ensemble_id` parameter for now. That is, any value is valid, and we won't actually connect it to the `ensemble` table yet.

**Comment by markusdregi** [comment]
To address the most fundamental thing first. I think we have a very different take on what a record is to be... In particular, in `ert3` a record is the data elements that can be passed through the workflows and put into storage. This is currently nothing by rather flat JSON data. I'm currently formalising it as https://github.com/equinor/ert/pull/1415/files#diff-5a50570962a2ffe99bfb969b833a0ab8cce42b5365b790495171b994475adddd (Note that this is very much work in progress!).

The most important thing here is that parameters, constant structured data and output can all be treated as records. We might have to type them or at least annotate them according to your needs to separate between them, but they need to fundamentally be the same data format(s). And my plan was that that would be the record.

I'm thinking that we could later also introduce a `BinaryRecord`, `BlobRecord` or `OpaqueRecord` that is basically what you are describing here. But I first wanted to get the current data represented as records such that we can build upon that before we extend the scope 🤔

**Comment by oysteoh** [comment]
> To address the most fundamental thing first. I think we have a very different take on what a record is to be... 

I think that is correct, and our technical planning turned out to be much more of a discussion regarding what a record should be and how and where to store metadata - thus we need more time with you clarifying this 👍

**Comment by dotfloat** [comment]
We've had another discussion:

First of all, I'd like to point out that all useful data is structured data. From ERT Storage's perspective, it doesn't matter if it's a JSON, CSV, or a cat picture. We can't interpret the data between stages. We still want to store it and therefore the above description of `record` would still make sense.

From ERT3's perspective, at the beginning they need to create the parameters (or coefficients) from priors. The can do this, store the produced file into a record named `coefficients`, and forget about any other context. However, for ERT Storage and its consumers to work, we need to keep additional information, such as a link between parameters and priors. We need to have the flexibility to store data in our chosen format (currently as a dense float array).

The current model of ERT Storage requires for every object to be fully specified when it comes in. You cannot add a stray parameter vector after-the-fact. Thus, when initialising an ensemble run, you're required to specify all of its parameters, in the same JSON. We can discuss whether this is a good approach, but this is the current one. Strictness is a virtue in this regard, is my opinion.

ERT3 and its forward models, however, want to have a single namespace from which they can obtain data. That is, you don't want to distinguish between the source of parameters and other data -- they're all "records".

One solution to this is that we add a new endpoint:
* `POST /ensembles/{ensemble_id}/records/{name:str}/{realization_index}/data`
  Renamed endpoint. This is for uploading arbitrary data as described in https://github.com/equinor/ert/issues/1407#issuecomment-779256189
* `POST /ensembles/{ensemble_id}/records/{name:str}/{realization_index}`
  New endpoint. It takes a simple JSON object and is meant for linking a non-blob object to a record name

Then the happy path for ERT3 is as follows:
1. Create ensemble, with all the coefficients, as a single JSON object. Post to `/ensembles` and get `ensemble_id` for server.   (This happens today in old ERT)
2. Post `{"type": "parameters", "mimetype": "application/json"}` to `/ensembles/{ensemble_id}/records/coefficients`
3. The user asks for `coefficients` record, GETs `/ensemble/{ensemble_id}/records/coefficients/data`, receives JSON in the format that ERT Storage has chosen
4. The user can now use this JSON data directly, convert it using a unix step, or maybe ERT3 can have a pre-baked `convert: json2csv` option that they can add to the input
5. The output of the user's stage is some intermediate step, so we can't interpret the data. The output is uploaded as-is to `/ensembles/{ensemble_id}/records/{output_name}/{realization_index}/data`

The advantage of this is that:
1. The internals of how a parameter should be stored is kept, and is possible to modify later on
2. The API will be stable, enough that the structure of a JSON parameters object will be set in stone
3. The parameters aren't duplicated -- the alternative is that ERT3 uploads the parameters in one format to create and Ensemble, and then uploads a record as a blob in its own chosen format, thus uploading the same data twice.
