### ISSUE TITLE
Flatten endpoints

### ISSUE THREAD

**Issue by dotfloat** [equinor/ert#1420]
I'm starting to really dislike the endpoint scheme that we've chosen for ert storage. After we add workspaces and experiments, we'll end up with:
```
GET /workspace/123/experiments/456/ensembles/789/responses/0/data
```
It's excessively verbose. Note that each ID is unique, so we don't really need to specify eg workspace ID when we refer to ensemble's ID.

Perhaps we could replace it with the following scheme:
Everything is top-level:
```
GET /workspaces/<id>
GET /experiments/<id>
GET /ensembles/<id>
GET /responses/<id>
```
And we `POST` to the parent node in the hiearchy:
```
POST /workspaces # this is a root element so it doesn't have an ID we need to specify 
POST /workspaces/<id>/experiment
POST /experiments/<id>/ensemble
POST /ensembles/<id>/response
```
The singular form of the resource name in the end is somewhat deliberate. Spitballing here.

Let `parent` and `child` be two resource, where each `child` has `parent` as its parent. The general scheme is as follows:
* `GET /parents`: List all parents
* `GET /parents/<id>`: Get `parent` for that particular `parent_id`
* `GET /parents/<id>/child`: List all children for that particular `parent_id`
* `POST /parents/<id>/child`: Add a `child` with that `parent_id`
* `GET /childs`: List all children
* `GET /childs/<id>`: Get a singular child

I'd like to get the opinion of people. @jondequinor @mortalisk

**Comment by mortalisk** [comment]
Looks fine to me. I also prefer the flatter style for ease of implementation and debugging.

**Comment by mortalisk** [comment]
If we were doing REST, the principle to follow would also say that how a resource identifier is constructed is as important as e.g. which letters and numbers are found in a UUID.

**Comment by dotfloat** [comment]
Currently we're sending and receiving `id`s as `int`s in JSON. Wrt. UUID, it could be smarter to send them back-and-forth as `str`s in the event that we change from incrementing int IDs to UUIDs. If the user sees it as a `str` then there will be no change to the API and it's not like they're going to be doing any ID-based arithmetic.

:thinking:

**Comment by mortalisk** [comment]
I did not intend to talk about UUIDs. Me talking about UUID is only a device to make you realize that the entire URI structure is irrelevant if you are doing REST. Just as a client of a DB should not try to construct a UUID and guess the correct one for finding the correct item, a user should not try to guess what the URI of a resource is by concatenating values. It should be handed to the user by some mechanism in its entirety. The entire URI should be seen as the ID of the resource. My point was that if the API is designed RESTfully, then you proposed changes would by design be a server side change only, and not affect any client at all, as RESTful clients identify resources by URIs and not by constructing URIs (except if the mechanism for constructing URIs are described in the document definition, and the client explicitly told to do so, e.g. as in html forms)
Again, this is IF you are aiming at RESTful qualities. It is fine to make something that is not REST and then you can also do what you want to do regarding URI structure, only any change will then impact you clients.

**Comment by oysteoh** [comment]
This is not actionable as we are writing a new api with flattened endpoints and we are not aiming for flattening those we currently have in ert and are about to abandon.
