### ISSUE TITLE
Publish and fetch data from blob storage

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1493]
Make sure that we can publish and fetch data to the blob instance via the command line in Azure.

**Comment by markusdregi** [comment]
Note, it does not have to be directly via the command line, in the sense that it is perfectly viable to write a script that does it. What we want to achieve is to be on the Azure cluster, run something along the lines of `ert-blob-poc-publish <some-file-name>` and get the file uploaded. Second, we want to be able to run `ert-blob-poc-fetch <some-file-name>` and retrieve the same in the file specified. We might also have to pass some resource id's as well to be able to get the same data when fetching...

**Comment by dotfloat** [comment]
Here's my POC: https://gist.github.com/dotfloat/b5cf5a61bd227e922b7576f0b33a79c1

I require the user to specify the following environment variables:
1. `ERT_CONNECTION_STRING`: The connection string to Azure Storage
2. `ERT_CONTAINER`: **(Optional)** Container in which to put the blobs (defaults to `fmutest1`)
3. `ERT_ENSEMBLE_TOKEN`: Some random string in order to differentiate blobs between runs
4. `ERT_REALIZATION_INDEX`: **(Optional)** integer to differentiate between forward-models within the same run. (defaults to `None`)

Usage:
```sh
pip install azure-storage-blob
export ERT_CONNECTION_STRING="<Up to you ;)>"
export ERT_ENSEMBLE_TOKEN=$(python -c "import uuid;print(uuid.uuid4())")
export ERT_REALIZATION_INDEX=5
python ./ert-blob-poc-publish /bin/bash
python ./ert-blob-poc-fetch bash
diff bash /bin/bash  # no output means they're equal
```

**Comment by markusdregi** [comment]
We are using this successfully @dotfloat 👏
