### ISSUE TITLE
Bug in run_analysis

### ISSUE THREAD

**Issue by joakim-hove** [equinor/ert#151]
Bug in line 58 here: https://github.com/Statoil/ert/blob/master/python/python/ert_gui/tools/run_analysis/run_analysis_tool.py should create a RunContext.

**Comment by andreabrambilla** [comment]
I can try to have a look at this, but I definitely need more details. 
By RunContext I guess you mean `res.enkf.ErtRunContext` right? 
Also, what is the problem here? Is it actually a bug, in the sense that something does not work correctly? or are we talking about making the code "nicer"? (as in "that functionality is already implemented there, let's use it instead of re-implementing)

**Comment by geirev** [comment]
When I try to run RML I get the following error message:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ert_gui/tools/run_analysis/run_analysis_tool.py", line 58, in run
    success = es_update.smootherUpdate( source_fs , target_fs )
TypeError: smootherUpdate() takes exactly 2 arguments (3 given)

**Comment by joakim-hove** [comment]
This is being fixed here: #152 - I think

**Comment by jondequinor** [comment]
@frode-aarstad did this resurface?

**Comment by frode-aarstad** [comment]
@jondequinor no, i tried to link to issue 151 in ert-storage

**Comment by jondequinor** [comment]
> @jondequinor no, i tried to link to issue 151 in ert-storage

Could you close this then?
