### ISSUE TITLE
More flexible serialization within transmitters

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1555]
Right now each transmitter will do a check on mime, and then serialize based on that mime. E.g. 

```python
if mime == "application/json":
    await f.write(json.dumps(record.data))
elif mime == "text/csv":
    …
```

It would be better if we could use a mime to serializer registry like so:
```python
serialize = transmitter_serializers.get_serializer(mime)
await f.write(serialize(record.data))
```

Somewhere else, the registry would be built like this (handwavy):
```python
transmitter_serializers.register("application/json", json.dumps)
```

Depends on #1469

**Comment by jondequinor** [comment]
A benefit with this registry is that we can use the registry to validate user provided configurations. If the user provides numerical data in a `.tiff` format, we can fail given that a serializer for tiff files does not exist.

**Comment by jondequinor** [comment]
@sondreso any points you like to discuss?

**Comment by sondreso** [comment]
This label was added following another discussion, and if I remember correctly the thought was that since @DanSava was moving common functionality into the base Transmitter class, there was a question whether this would be needed afterwards or not. Looking at the code now, I still think it makes sense to implement this, event though the transmitters have common code for dumping and loading from files. As you say, it will provide a much more extendable and concise implementation :slightly_smiling_face:
