### ISSUE TITLE
Create tests for the data extraction to ert-storage

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1594]
The data extraction done in `ert_shared.storage.extraction` is currently not being tested. Mostly due to creating unit-tests requires a full ert-setup being run. We should create an integration test for `ert-storage` integration with `ert`. This should be part of our regular ci-workflows.

One possible solution is to run poly-example with `--enable-new-storage` and verify that the data is ends up in the ert-storage database.

**Comment by markusdregi** [comment]
**Definition of done**
All public functions in `ert_shared/storage/extraction.py` is tested, both for the happy path and the not so happy path! I suspect the easy way out is to make some of the functions private ;)

**Comment by markusdregi** [comment]
If we are to do a full blown integration test it would be beneficial if we could do a small reservoir setup, using for instance SPE1 + flow or snakeoil, such that we get summary data.

Otherwise, we could do a test where we mock the `enkf_facade`, either by mocking it globally, or by changing the interface such that the necessary objects (`enkf_facade` and `server`) are passed explicitly.

**Comment by dotfloat** [comment]
Spawned 3 issues. When they are resolved then we can look at any stragglers and make new issues or resolve this.
- [ ] `post_ensemble_data` #1669 
- [ ] `post_ensemble_results` #1670
- [ ] `post_update_data` #1671
