### ISSUE TITLE
Run examples from ert3 and visualize with webviz-ert 

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#1655]
Run the poly and spe1 examples and make sure they are possible to visualize correctly

Relates to #1550

**Comment by markusdregi** [comment]
After the merging of #1693 the records are now stored in `ert-storage`. However, a few things popped up during the little testing I did:

**No metadata**
ert3 does not publish metadata, which makes webviz-ert crash due to metadata being `NULL`. See https://github.com/equinor/ert-storage/issues/117 for the proper fix.

**Unsupported parameter layout**
ert3 publishes numerical data with their index, as in for instance the following parameter layout

```yml
coefficients:
  a: ...
  b: ...
  c: ...
```

However, webviz-ert currently does not support this kind of layout for parameters, only responses. The path of least resistance is probably to deal with this discrepancy in `ert3` by publishing `coefficients.a`, ... as single value parameters. There is then no formal connection anymore between the groups of parameters in storage, but webviz-ert should then readily be willing to plot them. The other alternative is to agree upon a minimal definition of a numerical record that allows for groups of parameters and that can be visualized by webviz-ert. I suspect this is more work, but probably where we would like to go in the long term.

Other issues might also be present 🤷🏻

**Comment by dotfloat** [comment]
Can we spawn issues from this, @markusdregi ? I'm uncertain what there is anything to do or if you're the one doing it.

**Comment by markusdregi** [comment]
Created https://github.com/equinor/ert/issues/1720 and https://github.com/equinor/ert/issues/1721 as actionable issues.

**Comment by markusdregi** [comment]
**Update**
I tried testing the ERT3 side of this now and hit an issue documented in https://github.com/equinor/ert-storage/issues/135.

**Method of testing**
- Install ert (with storage extra), ert-storage and webviz-ert from main branches
- Start a new ert-storage instance using `ert3 service start storage`
- Create a workspace for testing by `ert3 init --example=polynomial`
- Move into the workspace with `cd polynomial`
- Run the evaluation experiment using `ert3 run evaluation`
- Visualise the results running `ert vis`

**Status**
The above gives the following error if trying to visualise the reponse:

```
INFO:     127.0.0.1:62898 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=0 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62900 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=1 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62901 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=2 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62902 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=3 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62903 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=4 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62904 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=5 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62905 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=6 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62906 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=7 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62907 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=8 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:62908 - "GET /ensembles/b564474f-9bc4-4e2a-8d77-0b06ce5be668/records/polynomial_output?realization_index=9 HTTP/1.1" 404 Not Found
```

This issues is hence blocked by: https://github.com/equinor/ert-storage/issues/135

**Comment by markusdregi** [comment]
This seems to be working as expected now :tada:
