### ISSUE TITLE
Ensemble evaluator using same port as ert-storage

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#1676]
When ert is launching ert-storage, it is binding a socket, by default, on 127.0.0.1 starting on port 51820. The ee is trying to bind a socket on the servers public ip address using the same port range. As they are not bound on the same ip, it fails to detect them as open. 

A solution is to bind on  0.0.0.0, thus ensuring that it is discoverable on both local and public addresses.

**Comment by sondreso** [comment]
Reopened by #1701

**Comment by jondequinor** [comment]
Yeah that's our main hypothesis.

**Comment by oysteoh** [comment]
This line closes the socket
https://github.com/equinor/ert/blob/master/ert_shared/ensemble_evaluator/config.py#L38

according to this post
https://stackoverflow.com/questions/14388706/how-do-so-reuseaddr-and-so-reuseport-differ 

binding to a socket which is in closing state ( we never know exactly the amount of time it takes for us to close it apparently ) can lead to undesired side-effects.

```Note that binding a socket to exactly the same address and port as a dying socket in TIME_WAIT state can have unexpected, and usually undesired, side effects in case the other socket is still "at work", but that is beyond the scope of this answer and fortunately those side effects are rather rare in practice.```  

I also wonder if it makes sense at this point when trying to fix this issue is to merge the two codebases dealing with sockets and reserve these on ERT startup in a fixed order and keep track of which ports used and by that not having two codesnippets looping through the same range of available ports and maybe with that introduce the possibilities of race condition.

**Comment by oysteoh** [comment]
Still have some flakyness when testing due to ports being opened and closed and by that hitting eachother at times. Tried to solve it with random picking ports in range along with using in most of the tests a much bigger range of valid ports. `reuse_addr` needs to be in place still as the evaluator is keeping an instance of the config but launches async websocket server which creates sockets out of port from config - which means it will ( could at least ) bind multiple times to the same port. This will require refactoring of the ensemble evaluator to fix.

**Comment by markusdregi** [comment]
Resolved by: https://github.com/equinor/ert/pull/1764
