### ISSUE TITLE
Stop using metadata for record logic

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1710]
**Context**
In https://github.com/equinor/ert/pull/1693 `ert3` started using the numerical record endpoints in ert-storage. However, two pieces of information that needed to be able to pass a record to ert-storage, get it again and be able to return a record that is equivalent to the one provided originally, namely; the ensemble size and the record type.

The ensemble size is available for experiments, however `ert3` is currently using a special experiment to store the records that belongs to the workspace. This does not have a uniform experiment size and hence `-1` is passed.

The record type is also needed to be able to separate between `{"0": 42}` and `{0: 42}` when restoring after a get.

**Suggestion**
It is bad practice to store data for which logic is based upon in metadata as this puts the burden of migration on the client instead of the storage instance. Hence we should resolve the two issues above (probably by different means) so that the `ert3` implementation again becomes oblivious to the content of the metadata.

**Comment by markusdregi** [comment]
The need for storing of the record size relates to #1631

**Comment by DanSava** [comment]
Did a bit of investigation and found the following things. Storing the ensemble size together with their record as part of the metadata is only required because we are trying to store and retrieve RecordCollections. 

And because there is no internal representation of a record collection in storage we are forced to use this hack of storing the ensemble size together with the record as part of userdata in order to be able to reconstruct the record collection. Also as it is stated in the description that would not be a problem if we would not be storing records as part of the workspace ensemble, which is created with a size of `-1`. 

The use of the RecordCollection is limited to the loading of information into storage and setting up some preparation before the evaluation starts I think it would be a better idea to convert the RecordCollection class to something like a TransmitterCollection class that would manage a collection of transmitters associated with the records that have been stored into storage.

**Comment by eivindjahren** [comment]
This issue is framed in terms of ert3, and I believe it is still ert3 specific even if ert-storage is involved. Feel free to reopen and rephrase the issue in terms of the current development direction.
