### ISSUE TITLE
Better handling of state and state transitions of ensembles

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#1717]
Spawned from: #1691

This is blocked on the design issue if the assignee wants a design discussion. If not, it is possible to pick this up, but definition of done is:

- Low branching factor in state handling
- Preferably use a conventional pattern
- Should facilitate discussions that are more like "_why is bug a happening when going from state A to state B in system X?_", and less like "_why is this bug happening in system X?_". I.e. state related problems (incurred by networking issues or misbehaving, distributed actors) should be limited in scope, and easier to isolate. [Further reading](https://medium.com/dotcrossdot/hierarchical-finite-state-machine-c9e3f4ce0d9e).

**Comment by markusdregi** [comment]
Is this actionable? If so, could you provide some information?

**Comment by jondequinor** [comment]
I made an attempt at implementing this with a basic hierarchical state machine. By basic I mean without the extensions defined by statecharts (conditions on transitions, entry/exit actions, etc).

A hierarchical state machine is a state machine that allows a state to be a state machine.

With the basic HSM, I modeled a small portion of an ensemble (one step with two jobs) where the running state of the step was a state machine that encapsulated the states of the two jobs. So the state of the step at some point becomes a state machine (running), that itself is driven forward by events. The running step state machine is made up of two job state machines.

![Untitled Diagram(4)](https://user-images.githubusercontent.com/53553193/122452422-87d15e00-cfa9-11eb-8b89-9915004567a5.png)


Events are dispatched to the topmost state machine (the step) and propagated to the lower levels. This is contrary to the ultimate hook pattern, where events are supposed to propagate towards the "higher levels" if not handled by the lower levels. But that leads to complex dispatching in our case, because each realization will be disjoint from each other. So if an event comes in, you'll need to locate e.g. the correct job in the correct realization. You have a bazillion leaf nodes, which isn't common it seems.

By introducing multiple realizations, we also get a concurrent state machine, since the state of any realization can transition independently.

It is suggested by someʷʰᵒ that you use OOP to make implementing HSM smoother. This way, the code could be modularized into ens, real, step, job; as well as having the various implementations encapsulated. Imagine an API like this:

```python
ens_state_machine = EnsembleStateMachine(ensemble)
…
ens_state_machine.dispatch(cloudevent)
```

Where `EnsembleStateMachine` is

```python
class EnsembleStateMachine(StateMachine):
    def __init__(self, ensemble: _Ensemble) -> None:
        for real in ensemble.get_reals().values():
            self.add_substate(RealizationStateMachine(real))
            # add transitions here
```

Still, it's quite complex. Maybe I've misunderstood something.

Anyway, I will look into a simple behavioral tree implementation of the same thing.

**Comment by jondequinor** [comment]
Code here https://gist.github.com/jondequinor/45eb9a1f6454bbc6fb1afdc22a5309d7

**Comment by sondreso** [comment]
This issue is not very actionable in its current state, so will close it.
