### ISSUE TITLE
Make it possible to visualise ert3 parameters using webviz-ert

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1720]
**Introduction**
Due to lack of agreement on what a numerical record is between `ert(3)`, `ert-storage` and `webviz-ert` the current numerical parameters that is posted during an `ert3` run is not possible visualise using `webviz-ert`.

**Suggested approach**
The suggested approach of this issue is to start posting the numerical records in `ert3` as single value numerical records. That is that `ert3.storage` takes the responsibility of translating between the `ert3` record `example: {"a": 1, "b": 2}` into `{"example.a": 1, "example.b": 2}` and back again when retrieving. This fix should be kept entirely within `ert3.storage` and would yield functioning software while waiting for the numerical record discussion to mature.

**Definition of done**
When running the examples in `ert3` it should be possible afterwards to visualise the parameters afterwards using `webviz-ert`.

**Comment by xjules** [comment]
Btw @markusdregi as parameters you mean actually ert `prior` generated parameters or any records?
Since, if it is an arbitrary record, the labels can contain any string labels.
`pd.Dataframe(data=[[1,2]], columns=["example.a", "example.b"]`

**Comment by dotfloat** [comment]
Thanks for elaboration on the issue. ERT Storage's "matrix" type supports labels. So in your example, there would be a record named `example` for some realization index, where we `POST` the following CSV:
```csv
 ,a,b
0,1,2
```
You can only `POST` and `GET` on the record level, ie, if you have all of your coefficients in a record named `coeffs`, then you'll have to fetch it in its entirety.

I think my misunderstanding was that you wanted to upload parameters as multiple records at once, but if you're just interested in uploading a single record with labels, then that would fit very well within our current understanding of what a "matrix" type is. (It's a multi-dimensional float64 matrix with optional string labels for each of its axes).

Having labels in parameters doesn't seem like is currently possible in ERT Storage, but we should probably put in effort into making it work rather than doing this particular workaround.

**Comment by dotfloat** [comment]
Had another look, if we are to split up the parameters inside a record into multiple records, we'll need to know what the labels are ahead of time. We need to submit the parameter names with the ensemble, and this can't be done after the ensemble has been created. This is done to be strict and allow for better internal consistency in the database.

That is, we need to know ahead of time that `example` contains labels `a`, `b`, `c`. We can't discover this when the data is uploaded, because then it's too late as the ensemble object has already been created.

**Comment by markusdregi** [comment]
We do however currently have the records being parameters at hand when making the experiment, so this could actually be solved still. But it becomes a bit cumbersome 🤷🏻 

Or we could allow for `parameter_names` to be set later as you say.

Or, we could fix this in `webviz-ert` by making it expand the parameter indices such that we can plot `example.a` :)

**Comment by oysteoh** [comment]
Work continues in https://github.com/equinor/webviz-ert/issues/157

**Comment by xjules** [comment]
> I still stand by the description in the issue. The only thing missing from that approach is that currently parameter names needs to be known up front. There are at least two ways to resolve this specific issue:
> 
> Either we can stop passing `["coefficients", "some_record"]` as the parameter names and instead pass `["coefficients.a", "coefficients.b", ..., "some_record.xyz"]`. In other words we will have to extract the index from the records when initializing the experiment.

I've actually suggested this earlier, only issue  is that we need to parse the parameter names/strings and make this a guideline for the parameter naming. Which might do. Just a small idea: Could parameter names be a json/dict, ie. the first level key is the record name while the second level key is the real parameter name: `{"coefficients":{"a","b"}}`

> 
> Or we can allow for adding new parameters post experiment creation in `ert-storage`. I think both makes sense 🤷🏻

This looks good too! What do others think? @dotfloat

**Comment by markusdregi** [comment]
Yes, I think that is a good idea. Especially into `ert3.storage` I think passing `{"coefficients": {"a", "b", "c"}` makes sense as layout. But I guess it makes sense to flatten it then such that what `ert-storage` gets is `coefficients.a`, `coefficients.b`, `coefficients.c`?

Earlier there has been some resistant to making this mutable, as mutable is always something that comes with its own peculiar things. We might have to go into that direction at some point, but I'm unsure whether this is the right time for that...

**Comment by xjules** [comment]
> I suggested it as a hack to work around ERT3 not knowing the parameter names at ensemble creation, but it _does_ know. So what would be the reason for post-hoc specifying the parameters?

Then we might store as individual records as we not longer care them being a single record. That's at least how I understood it.
