### ISSUE TITLE
Parallell ecplise simulations

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#177]
> Number of cpu’s pr job should not be picked up from the Eclipse data deck as done today . Instead, there should be a separate keyword in the config file defining number of cpus pr job.

**Comment by markusdregi** [comment]
And along the same lines:
> Eclipse runscript should handle the PARALLEL keyword in eclipse deck.

**Comment by markusdregi** [comment]
> there should be a separate keyword in the config file defining number of cpus pr job

It would still be the responsibility of the jobs in the forward model to utilize this. Unsure of the benefit.

> Eclipse runscript should handle the PARALLEL keyword in eclipse deck.

It is currently handled, however the parsing is quite simple and naive. Does not support includes. If we want to improve this, we should consider utilizing opm-common.

**Comment by markusdregi** [comment]
Could also be that this is related to Flow not supporting the parallel keywords, if so, that should at some point be resolved one way or another.

**Comment by markusdregi** [comment]
This is an issue of little value in its current form. Have you given any though to how this should be done in the future @eivindsm? A suggestion from me would be that:

A stage defines how many cores it needs, and in the case of Eclipse that would be a unix step. After which, when the stage launches the information of available cores are made available. When Eclipse launches we diff `NUM_PARALLEL` and the number of available cores and give a warning if they differ and either way run the simulation with the minimum of "available cores" and `NUM_PARALLEL`? Does that sounds like a reasonable solution? If so, I can streamline the issue a bit for future work...

**Comment by eivindsm** [comment]
Not sure how to handle the issue, but I subscribe to the original issue that it should be possible to configure parallel execution in the config file, not relying on having an eclipse DATA file. I have seen examples where there was no need for eclipse, but in order to execute another forward component with multiple cores a face DATA file had to be included, which is simply not very logical nor user friendly. In the future, eg ert3, we would like the ability to execute different forward model components with different hardware configuration, aka staging. If we only cater for || execution on the cores belonging to same node this should not be to difficult, but if we also are to cater for multiple nodes over eg Infiniband, the issue becomes more involved. For the special, but most common case, where only the reservoir simulator is to be executed in ||, I would like us to keep the possibility to parse the DATA file and deduce that it is a || run  without double configuration need.

**Comment by markusdregi** [comment]
I completely agree. Multi-core modelling ought to be possible without having to introduce a datafile in the setup... I suggest that to avoid double configuration and still maintain a sane and usable system we define the number of cores in the stage and then cater for the possibility to template that value into the datafile via standard methods to avoid double configuration 👍🏻

**Comment by markusdregi** [comment]
This will naturally come up during future development and testing in Azure.
