### ISSUE TITLE
Log when MAX_RUNTIME kicks in

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1886]
After https://github.com/equinor/ert/pull/1636 there is information available in the GUI when a realisation has been killed due to max runtime. However, this information is not available when running via the CLI.

We should also log this event such that this information is available when users are running in the CLI.

**Comment by mortalisk** [comment]
https://github.com/equinor/ert/blob/master/ert_shared/cli/monitor.py#L77 is supposed to print if any jobs failed due to any error. Is this not sufficient? Or does it not work?

**Comment by mortalisk** [comment]
Tried with 2021.07.00 with --enable-ensemble-evaluator (as this is the only code-path that has feedback upon MAX_RUNTIME induced failure). I got the following:
```
Simulations failed with the following error: Simulation failed! All realizations failed!
5 jobs failed due to the error: The run is cancelled due to reaching MAX_RUNTIME
```

**Comment by sondreso** [comment]
So the problem is then that info about being killed due to max runtime is not being displayed without the ensemble evaluator (which is not on by default in the current stable nor on the main branch)?

While we aim to make the evaluator default in `2021.09`, I think we should include some indication in the old code path as well. It will be difficult to display it in the GUI and/or CLI since there are few ways to communicate this information without the evaluator, but I think a simple timeout callback that says something like "Realization x was killed since it reached MAX_RUNTIME" is better than nothing. See https://github.com/equinor/ert/blob/main/res/job_queue/queue.py#L484-L508

**Comment by mortalisk** [comment]
Seems to also have been added to legacy evaluator in https://github.com/equinor/ert/pull/1829, so it works there as well.
Should maybe be logged to a log file as well?
