### ISSUE TITLE
Replace network logger functionality for job runner

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#1990]
Replace network logging functionality in job runner / job_dispatch

**Comment by sondreso** [comment]
I assumed the issue was meant for the job runner, as the evaluator does not have any network logging, so changed the title and description to reflect that.

**Comment by sregales-TNO** [comment]
Is there something already made to replace Network Logger? If not what stage of development is it at discussion, design, or implementation? and if some of these stages are already done, where can I find the notes for them?

**Comment by jondequinor** [comment]
https://github.com/equinor/fmu-logging/ 
https://fmu-docs.equinor.com/docs/ert/architecture/dev-strategy.html#logging

There's been a couple of meetings you were invited to, not sure if you joined? At least i didn't.

**Comment by ManInFez** [comment]
@sregales-TNO This will be our new and shiny azure logger :)

**Comment by oyvindeide** [comment]
We are replacing the functionality with the built in `logging` module, not creating something new, per se..

**Comment by sregales-TNO** [comment]
So, to be sure, we are not importing anything from fmu-logging.

**Comment by oyvindeide** [comment]
> So, to be sure, we are not importing anything from fmu-logging.

Correct, we should not make that a dependency of `ert`, it will be up to the user to add handlers that satisfy their needs.

**Comment by sregales-TNO** [comment]
Related to issue #1778 I decided to look into loguru (a python log library) who is also available for C++ and Cython.
Plus:
- It is easy to use (a more comprehensible API) 
- Faster, log strings are formatted at a different layer
- Can easily migrate from python logging module*
- Can be used with C++ and Cython
Min:
- We currently use logging.conf and load it with logging.dictConfig this will not be possible out of the box. https://github.com/Delgan/loguru/issues/374#issuecomment-738279641
- It's another dependency to manage
*When it comes to our use case because of logging.conf that will not be the case

**Comment by oyvindeide** [comment]
Will it be able to propagate the logs from C++ into the python logger/the python implementation of loguru? My 2 cents is that I dont really see the advantage over the built in logging module. What extra functionality do we get that we currently need? And do we lose something?

**Comment by sregales-TNO** [comment]
There is documentation of configuring the depth of loguru in order to capture logs from cython, but this will only include the message and not metadata such as function thread and more. this is because Loguru (and logging generally) heavily relies on Python stack frames https://loguru.readthedocs.io/en/stable/resources/recipes.html?highlight=cython#using-loguru-s-logger-within-a-cython-module. Other than Cython there is no documentation on C++ logging propagating to python. My conclusion is similar to yours, I don't see the advantage of loguru over built in logging.
