### ISSUE TITLE
Running tests on macOS, dylib vs. so

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2029]
Running the following seems to work, but I get a few warnings and errors.

```console
$ pytest -sv tests/libres_tests/res/enkf/test_analysis_config.py
```

The errors are of this type:

```console
Failed to load library:rml_enkf.so Error:dlopen(rml_enkf.so, 2): image not found 
** Warning: failed to load module from rml_enkf.so.
```

The first error originates in the code below:

https://github.com/equinor/ert/blob/35984a1d08f3fdc3764caed7e0220f740d1ceb77/libres/lib/analysis/analysis_module.cpp#L150-L182

Changing [site-config](https://github.com/equinor/ert/blob/main/share/ert/site-config#L16) to `rml_enkf.dylib` and re-running tests gets rid of most of these errors, but not all since some [config-files in /test-data](https://github.com/equinor/ert/blob/main/test-data/local/simple_config/analysis_config) specify `rml_enkf.so`.

Do we want to be able to run successfully if site-config is updated to `rml_enkf.dylib`?

Should we hard-code `.so` in config-files?

**Comment by dotfloat** [comment]
Python will compile C Extensions with `.so` on every platform other than Windows (where it's `.dll`). We should do the same thing perhaps in libres by setting the soname in CMake.

**Comment by BjarneHerland** [comment]
Like Feda, I'm on MacOS where Python compiles C Extensions with suffix ".dylib". It is simple to patch the lib-name in the test by e.g. putting something like this

`LIB_EXTENSION = "dylib" if uname()[0].lower() == "darwin" else "so"`

here

https://github.com/equinor/ert/blob/996406c11d247755151f9409d523d28d14ac36b0/tests/utils.py#L3

then use it like this

`ConfigKeys.LIB_NAME: "rml_enkf.{}".format(LIB_EXTENSION)`

instead of the hardcoded .so

https://github.com/equinor/ert/blob/996406c11d247755151f9409d523d28d14ac36b0/tests/libres_tests/res/enkf/test_analysis_config.py#L91

Now, the AnalysisConfig built from dict has the correct library-suffixes.

This test compares a config loaded from file with the config build from dict. So unless we also patch suffixes in the config loaded from file, the test actually fails (as opposed to just spew out warnings).

The complication is that loading config from file happens in C++ in a rather subtle way, triggered from here

https://github.com/equinor/ert/blob/996406c11d247755151f9409d523d28d14ac36b0/res/enkf/analysis_config.py#L140-L151

One way to patch this config loaded from file is to change this method

https://github.com/equinor/ert/blob/996406c11d247755151f9409d523d28d14ac36b0/libres/lib/enkf/analysis_config.cpp#L314-L316

to something like this (Note PoC! Should probably be an util-method since it is likely to be useful elsewhere):

```
bool analysis_config_load_external_module(analysis_config_type *config,
                                          const char *lib_name,
                                          const char *user_name) {
    analysis_module_type *module = analysis_module_alloc_external(lib_name);
    if (module != NULL) {
        if (user_name)
            analysis_module_set_name(module, user_name);
        config->analysis_modules[analysis_module_get_name(module)] = module;
        return true;
    }

    std::string lName(lib_name);
    const std::string suffix = ".so";
    const auto at = lName.find(suffix, 0);
    if (at == std::string::npos) {
        fprintf(stderr, "** Warning: failed to load module from %s.\n",
                lib_name);
        return false;
    }

    fprintf(stderr, "** Warning: fallback to .dylib for %s.\n", lib_name);
    lName.replace(at, suffix.length(), ".dylib");
    return analysis_config_load_external_module(config, lName.c_str(), user_name);
}
```
The steps outlined above are sufficient to make the test work as well as ensuring the correct library is loaded. Note that these changes do not get rid of warnings to console, which should be subject to proper logging. However, this IMO is a separate issue.

**Comment by dotfloat** [comment]
Adding the following to `CMakeLists.txt` and removing any reference to `.dylib` in libres should be enough to fix this problem.
```cmake
set(CMAKE_SHARED_LIBRARY_SUFFIX ".so")
```
