### ISSUE TITLE
How should we configure transformations? 

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2123]
Currently the specification and configuration the transformation are done in the input/output itself. This leads to a lot of cross validation, when the options are in reality mutually exclusive. We should look into a better way of doing this.

**Comment by sondreso** [comment]
Suggestion using discriminated unions in pydantic (Available in the newest [version 1.9.0](https://github.com/samuelcolvin/pydantic/releases/tag/v1.9.0)), while also making it possible to use a plugin system to provide new config types for certain fields is implemented here: https://github.com/sondreso/ert/tree/config-example

The file [test_simplified_configs.py](https://github.com/sondreso/ert/blob/config-example/test_simplified_configs.py) is the starting point for the example.

**Comment by jondequinor** [comment]
I'm going to propose we hold off on the plugin approach for now, and keep the current configuration, but extend it as follows:

We add a `transformation` field, but it's not necessary for the user to provide it—we will provide it via translation.

1. Individual field validation should be atomistic, with some prevention of foot-shooting, like exclusivity.
2. A posterior root validator populates the `transformation` field should it be empty, using a holistic, imperative approach. This is the translation. Every field has to be considered to produce a valid configuration. This imperative approach conflicts with the plugin approach, because a single discriminator isn't sufficient to select a transformation. For example:

    Let's say the default `smry_keys` is `*` and the user creates this configuration:

    ```yaml
    input:
    -
        record: eclsum
        location: case/SPE1.UNSMRY
    ```
    Shouldn't the eclsum transformation be picked here? If the user wants all keys, this configuration seems natural. But ending up with an eclsum transformation is a couple of steps away (guess mime → application/x-usmry → no other viable transformations → eclsum transformation).
    
    Another example where there's no MIME, but explicit keys:

    ```yaml
    input:
    -
        record: eclsum
        location: case/SPE1
        smry_keys: ['LOLPT:*', 'WTF:ROFL']
    ```
    No MIME, but `smry_keys` makes this an obvious case of an eclsum transformation.


3. I don't think we should expose `transformation` in configuration _to the user_. It's easy to argue it's an implementation detail. It's too much _how_, not _what_. We should think policy, not mechanism in these configurations.
4. User configuration should be, and almost always is, messy, contradictory, full of implications and omissions. It's unreasonable to require the user to provide the perfect experiment/ensemble spec with fully defined transformations. It's best if the user provides the information she has in front of her, and that's that. If there's ambiguity, it's easier to ask forgiveness than to ask about a bunch of details up front. (Only true when we're talking about configuration)
5. If fields—individually—are not sufficient to produce a transformation, then I'm not certain there is a good pluggy API possible, without passing entire configurations. This is probably not what we want, because these configurations should probably be allowed to vary independently from plugins.

Working example (from https://github.com/jondequinor/ert/blob/ad674dbaf1acd55a7a115640bd9f14db76f96d05/test_translator_approach.py#L71-L100)

```python
class StageIO(_StagesConfig):
    record: str
    location: str
    mime: str = ""
    is_directory: bool = False

    smry_keys: Optional[List[str]] = None
    transformation: Optional[TransformationConfigBase]

    _ensure_record_mime = validator("mime", allow_reuse=True)(ensure_mime("location"))

    @validator("smry_keys", always=True)
    def _no_is_directory(cls, v, values):
        if values["is_directory"] and v:
            raise ValueError(f"cannot extract keys '{v}' from {values['location']} (a directory)")
        return v

    @root_validator
    def setup_transformation(cls, values):
        if values["transformation"]:
            return values

        mime = values["mime"]

        smry_keys = values.get("smry_keys")
        if mime == "application/x-eclipse.unsmry" or smry_keys:
            kwargs = {"keys": smry_keys} if smry_keys else {}
            values["transformation"] = SummaryTransformationConfig(**kwargs)

        return values
```

Which produces:

```python
print(StageIO(record="eclsum", location="case/SPE1.UNSMRY").transformation)
print(
    StageIO(
        record="eclsum", location="case/SPE1", smry_keys=["LOLPT:*", "WTF:ROFL"]
    ).transformation
)

# SummaryTransformationConfig({'keys': ['*']})
# SummaryTransformationConfig({'keys': ['LOLPT:*', 'WTF:ROFL']})
```

**Comment by jondequinor** [comment]
After some discussion with @sondreso , we figured it's likely acceptable for users to explicitly configure transformations at this point, but that we'll aim for implicit configuration later on—or if transformations becomes hard to configure.

**Comment by jondequinor** [comment]
After coding and discussions, we're going to apply transformation configuration to `resource` entries in the ensemble configuration as well.
