### ISSUE TITLE
Use transformations for function step as well

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2165]
**Is your feature request related to a problem? Please describe.**
#2040 Introduced the concept of a transformation, but it only uses transformations for the unix step. We should also use transformations for the function step.

**Describe the solution you'd like**
Usage of transformation in the function step as well. The input transformation could be named something related to `kwargs` and the output transformation related to `dict`. 

**Additional context**
A PR resolving this issue should probably also remove the different IO type, as this is information/functionality that should reside in the transformation

**Comment by xjules** [comment]
Currently the transformations are to act as more complex `from_record_to_disk` or `from_disk_to_record` functions, which is fine for the `unix_step` as this job operates on files. On the other hand, `function_step` acts on variables directly (ie. not records and not files) and it does not fit into the concept of transformations as of now.

**Comment by xjules** [comment]
As we are working on more extensive ert3 configs (eg. snake-oil, drogon) it turns out that making `function_step` aware of the transformations might be beneficial: https://github.com/equinor/ert/blob/9ff386bf346dd3ccedee213886a3420b38f574c6/ert_shared/ensemble_evaluator/entity/function_step.py#L32 especially when providing (sub-recordtree) data to functions.

**Comment by markusdregi** [comment]
@xjules: Could you please provide some more insight into why this would be beneficial? :)

**Comment by sondreso** [comment]
This is no longer relevant, the function step should receive the data from the record directly.
