### ISSUE TITLE
`ESUpdate.smootherUpdate` results different on osx and ubuntu

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#2351]
**Describe the bug**
`ESUpdate.smootherUpdate` produces numerically different results on linux and osx.

**To Reproduce**
Steps to reproduce the behavior run on linux and osx and compare the results:
Using the snake oil case:

```python
shutil.copytree(os.path.join(source_root, "test-data/local/snake_oil"), "test_data")
os.chdir("test_data")
return ResConfig("snake_oil.ert")
res_config = setup_case(, )

ert = EnKFMain(res_config)
es_update = ESUpdate(ert)
ert.analysisConfig().selectModule(module)
fsm = ert.getEnkfFsManager()
sim_fs = fsm.getFileSystem("default_0")
target_fs = fsm.getFileSystem("target")
run_context = ErtRunContext.ensemble_smoother_update(sim_fs, target_fs)
es_update.smootherUpdate(run_context)
```
**Expected behavior**
Expect the results from the update to be identical, or at least very close, at the moment they are not.

**Comment by BjarneHerland** [comment]
Would like to have a look at this one. Two questions: 1) which module are used (ref your code above)?  and 2) which results are you looking at (what fil/property is different)?

**Comment by BjarneHerland** [comment]
The problem seems to be different implementations of `std::normal_distribution`. It has been reported before, for example here

https://github.com/RobotLocomotion/drake/issues/4361

The consequence for us is that ERT see different sequences of random numbers on Mac and Linux.

Compiling and running the MWE below produces different results on Linux and OSX
```
#include <random>
#include <iostream>

int main(int, char**)
{
   std::mt19937 engine(42);
   std::normal_distribution<double> distribution(/*mean=*/0.0, /*stddev=*/1.0);

   int firstRandom = engine();
   double randomNumber = distribution(engine);
   int thirdRandom = engine();
   std::cout << "First random=" << engine() << "  Normdist 2nd=" << randomNumber << "  third random=" << thirdRandom << std::endl;
}
```
This is essentially what ERT does (although with a different RNG)

https://github.com/equinor/ert/blob/e2a8371c0385dc845a621bbd186f3245cf1f91d9/libres/lib/enkf/enkf_util.cpp#L41-L45

but the problem turns out to not be the RNG itself but how it is mapped to the distribution:

**_OSX, both Rosetta and native M1, clang-1205.0.22.11:_**
`First random=669991378  Normdist 2nd=0.318902  third random=1914837113`

**_Linux, both g++ (Ubuntu 9.3.0-17ubuntu1-20.04) 9.3.0 and Ubuntu clang version 12.0.0-3ubuntu1-20.04.4_**
`First random=669991378  Normdist 2nd=-1.11188  third random=1914837113`

Note that the first and third random numbers are the same, but second random numbers mapped to a `std::normal_distribution` differs.

**Solution?**
The real question is how big impact different sequences have on end-results from ERT. Our current assumption is that different sequences produce (significally) different end-results **but I have not seen** hard evidence for this. If this assumtion holds, however, running the same simulation currently on Mac and Linux give different results, which is probably not desired.

We can re-implement the normal distribution to avoid differences between Linux and Mac but this means that the sequences will be different as compared to today. Which means that existing results can not be reproduced with new versions of ERT (assuming the assumption above holds).

**Actions**
Possible actions include

1. Check assumption above (should probably be done in any case)
2. Drop support for running actual simulations on Mac
3. Document that existing results can not be reproduced after some version
 
@markusdregi and probably our PO might want to consider this.

**Comment by markusdregi** [comment]
My suggestion would be that we:
- accept and (possibly) document that numerical results might vary between linux and MacOS and
- that we keep introducing tests into this domain that either only runs on Linux (which is by far our main target os) or by having different expected results in the test depending on whether the tests runs on Linux or MaxOS.

**Comment by BjarneHerland** [comment]
Reminds me of [Segals law](https://en.wikipedia.org/wiki/Segal%27s_law)  _(A man with a watch knows what time it is. A man with two watches is never sure.)_  😄 

I can wrap up tests as suggested. However, rocking the boat wrt stability of results from ERT (aka "document that numerical results might vary between linux and MacOS") must be done by someone else IMO.

**Comment by markusdregi** [comment]
Nice quote! 😎

I'll evaluate the need for document this, so that you can focus on the test 👍🏻

**Comment by oyvindeide** [comment]
Fixed in https://github.com/equinor/ert/commit/8260951d8b93917ae40f9abc666b19b178413502
