### ISSUE TITLE
Replace `int_vector_type *step_list` with `std::`

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#2416]

**Comment by joakim-hove** [comment]
I fully understand and support the desire to use `std::xxx` instead of `int_vector_type *` but just two comments:

1. Have you verified that the "default grow[1]" functionality of `int_vector`is not in action for this particular code?
2. Have you considered `std::vector<T>` - I think that is considered the "go-to linear container"?

[1]: Sorry if this is well known: https://github.com/equinor/ecl/blob/master/lib/util/vector_template.cpp.in#L27. This was a design which was very convenient for a special problem at hand - but in hindsight it was probably a grave mistake because the semantics of `xxx_vector_type` is different from `std::vector<xxx>` which inhibits a trivial wholesale search&replace refactoring.

**Comment by dotfloat** [comment]
Yeah, don't use `std::list`, use `std::vector<int>`. Also consider adding a utility function for converting between `std::vector<T>` and `T_vector_type`. (`std::list` is a doubly-linked list while `std::vector` is a contiguous array.)

@joakim-hove: The default grow functionality is okay-ish since it can be implemented by resizing a `std::vector`. However, the biggest issue I have encountered while trying to simplify it (a task which I have yet to manage) was all of the ownership semantics. There are private, shared, etc versions of a the vectors which means that `vector_type` cannot be backed by a `std::vector`. It seems like these alternative ways to allocate an array are niche. Do you know if it's possible to remove that functionality so we can implement `vector_type` with a `std::vector`?

**Comment by joakim-hove** [comment]
> The default grow functionality is okay-ish since it can be implemented by resizing a std::vector

Well - of course `std::vector<T>::resize()` must be used - backing a `xxx_vector_type` with `std::vector<xxx>`should be fairly simple, however getting rid of the `xxx_vector_type` api I have considered more complex. The problematic usage is the pattern:
```C++
// Create vector of zero size with default value 77:
int_vector_type * vec1 = int_vector_alloc(0, 77);
...
int_vector_iset(vec1, 4, 88);
/*
  vec1 = {77, 77, 77, 77, 88}
*/
```
whereas the following std::vector<int>`is just basically buggy:
```C++
std::vector<int> vec2;
...
vec2[4] = 88;
```
