### ISSUE TITLE
Move the responsibility of loading resources as Record to the workspace module

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2419]
You should be able to request resources from the workspace and have record(s) returned to you. This involves moving `load_collection_from_file` to the workspace.

**Comment by verveerpj** [comment]
Note: resolving issue #2420 will remove some validation code from the workspace. However, if this is done as proposed now by PR #2433 this will not yet remove the validation code for the resources. If PR #2433 is merged before this issue is resolved, the validation code for resources may need to be moved by the PR for this issue, or in a subsequent PR.
