### ISSUE TITLE
Session tests faild on komodo

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#2442]
```
self = <ert_storage.client.session.Session object at 0x7f20c43e52e0>

    def _resolve_url(self) -> str:
        """Resolve which of the candidate base urls to use."""
        for url in self._connection_info["urls"]:
            try:
                # Original code has auth token passed but is it actually used?
                resp = requests.get(f"{url}/healthcheck")
                if resp.status_code == 200:
                    return url
            except requests.ConnectionError:
                pass
        # Needs better exception message
>       raise RuntimeError("None of the Storage URLs provided worked")
E       RuntimeError: None of the Storage URLs provided worked

/prog/res/komodo/test-hash-py38-rhel7/root/lib/python3.8/site-packages/ert_storage/client/session.py:83: RuntimeError

Looks like an issue with base_url = localhost

```

**Comment by TerryHannant** [comment]
Tests failed in CI  due to two separate issues:

# ERT-storage server startup time
   As part of the integration tests setup an instance of ert-storage is started. A wait is performed (sleep)  to allow the server enough time to  full start before the integration tests are run. The sleep time initially (2s) used was not sufficient for the CI node, so the resolve this a larger value (30s) is used.  

# HTTP proxy
  Two of the unit tests were failing due to HTTP requests being incorrectly sent via HTTP proxy, which in turn was returning a 200 status code even though the requested URLs were invalid. To resolved this the proxy usage was explicitly disabled in the unit tests (by use of the NO_PROXY environment variable)
