### ISSUE TITLE
Create and use transformations for loading and saving json and yaml.

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#2565]
In ERT3 we are more and more performing file saving/loading/serialization via transformation classes. We do a lot of saving and loading of json and yaml files, we should look into creating and using a transformation for that, or modify an existing transformation to become aware of file/mime type.

**Comment by Blunde1** [comment]
`RecordTransformation` has been unlinked from `RecordTransmitter` https://github.com/equinor/ert/compare/c79674e116b0ddc6f6f170e03321d43750fab750...b988ec59db6c87b8a2517a3d27c762e8942744a8 and in the process modified to employ `Serializer` using the mime type.

Left: scan ert/ert3 to find places where `RecordTransformation` should be used instead of raw `get_serializer` or load/dump methods for json/yaml

**Comment by xjules** [comment]
My guess would be that we can close this issue since now `FileRecordTransformation` includes the required transformation functionality, ie. `json` and `yaml`.
