### ISSUE TITLE
Rename `get_int` to something more descriptive

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2720]
Should we try giving this one a better name @joakim-hove ?

https://github.com/equinor/ert/blob/09152c9a300fe90a4b1fc046f10c6e8118c5ada5/libres/lib/analysis/ies/ies.cpp#L588

**Comment by joakim-hove** [comment]
The analysis modules implement get and set methods for the fundamental types. This design has been chosen so that a user can set an arbitrary value with 
```
ANALYSIS_SET  MODULE_NAME VariableName Value
```
without the ert application needing to know the type or internal name of the variable. Now that we are close to having only one single analysis module it is natural to rework the entire system for updating the internal properties of an analysis module, so rather than rename this particular function I would suggest we wait a bit longer, and then rework the entire thing.

**Comment by dafeda** [comment]
Sounds good!
