### ISSUE TITLE
Improve Yaml error reporting

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#2750]
We should expect our users to write invalid Yaml at times. Currently this yields a stacktrace in the terminal. We should display the error message in a better manner.

**Comment by pinkwah** [comment]
We were discussing implementing [JSONSchema](https://json-schema.org/) for ERT 3 configs in a multi-day workshop. There is a validator library for Python, [jsonschema](https://github.com/Julian/jsonschema), which is also able to give better error messages.

The _massive_ benefit of using JSONSchema is that the schemas will be recognised by VS Code (and most other editors) and will give you live validation and autocompletion when editing ERT configs.

**Comment by lars-petter-hauge** [comment]
Perhaps not the correct issue to put this comment in, but since we're already talking about jsonschema and pydantic: the [autodoc pydantic](https://autodoc-pydantic.readthedocs.io/en/latest/) plugin provides an improved rendered version of documentation that we could really benefit from.

Otherwise agree with @pinkwah !

**Comment by markusdregi** [comment]
I agree with all the comments, but this issue was still just intended to get away from the stack trace currently dumped in the terminal if the files contains invalid YAML :)

**Comment by eivindjahren** [comment]
Closing as related to ert3, which is no longer the direction taken by the project.
