### ISSUE TITLE
Running ert3 experiments gives error message about __ensemble_records__

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#2760]
**Describe the bug**
ert3 run evaluation sometimes gives error message

`Experiment /ert/polynomial.__ensemble_records__ does not exist`

**To Reproduce**
TBD

**Expected behavior**
TBD

**Enviromment**
 - OS: RHEL7
 - ERT Release: main
 - Python version: 3.6
 - Remote/HPC execution involved: yes and no (Related ti Azure testing)

**Comment by verveerpj** [comment]
Steps to reproduce on my WSL2 (ubuntu 20.04):

In the polynomial directory, without a storage service running:
- ert3 init, this fails due to missing storage
- start storage with: ert3 service start storage
- ert3 run evaluation

Theory: It seems the `init `step failure is not properly detected. If we are still using a `.ert` directory to detect initialization, maybe we should remove that on `init` failure.

**Comment by jondequinor** [comment]
Was the failure logged to console, @verveerpj ? Thanks

**Comment by verveerpj** [comment]
The init failure? You get a timeout exception. So that is probably  not properly handled.
