### ISSUE TITLE
Conceptual description of `PartialSnapshot` and `Snapshot`

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2788]
The docstring of `PartialSnapshot` would in my opinion benefit from a more conceptual description.
Information like what is a `PartialSnapshot` and how does it differ from `Snapshot`.

Perhaps the module `snapshot.py` could start with a module docstring explaining why we are creating these new concepts and how they fit in with the rest of the system.

https://github.com/equinor/ert/blob/4f176e052a50b8d10c5489abfd372f17e6f97f18/ert_shared/ensemble_evaluator/entity/snapshot.py#L62-L68

**Comment by jondequinor** [comment]
Not going to pick this up right now, but here's a short introduction in case you're blocked by this:

The `Snapshot` is a more or less a dump of the state of the `EnsembleEvaluator`—it includes all information on realizations (ensemble members), steps and jobs. It's organized in a hierarchy, so a `to_json` method would look like this:

```javascript
{
    "reals": {
        "0": {
            "status": "RUNNING",
            "steps": {
                "0": {
                    "status": "SUCCESS",
                    "jobs": {
                        "0": {
                            "name": "my_forward_model",
                            "max_memory_usage": 200,
                            "status": "SUCCESS"
                        }
                    }
                }
            }
        },
        "1": { # real number 1
             …
         }
    }
}
```

If you have a `Snapshot`, you know everything the GUI needs to know to make a rendering like the one we have today. The GUI gets a `Snapshot` in its lap on evaluation startup and internalizes that.

All subsequent updates (a job finished, memory usage was updated), are communicated using the `PartialSnapshot` class. A `to_json` method for it, should there be a memory update in some job, would look like this:

```javascript
{
    "reals": {
        "0": {
            "steps": {
                "0": {
                    "jobs": {
                        "0": {
                            "max_memory_usage": 50000,
                        }
                    }
                }
            }
        }
    }
}
```

The GUI is sent a bunch of these (hundreds, thousands?) for an evaluation, and internalizes that partial information such that _its_ internal state is the same as the evaluators'. This has a likeness to [event sourcing](https://martinfowler.com/eaaDev/EventSourcing.html).

The `PartialSnapshot` also has an API that allows for easy mutation of a `Snapshot`. Also, if you have a relevant [`CloudEvent`](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md), a `PartialSnapshot` can be made from that. The forward models communicate to the evaluator using cloudevents, so that's benificial.

_(I'll probably edit this post, and use it as a basis for updating the docs. Others: feel free to do the same.)_

**Comment by dafeda** [comment]
Closing as stale
