### ISSUE TITLE
Return `Step` from `step_from_keys` (?)

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#2804]
`step_from_key` returns `Union[Function, Unix, None]` while `Step` is defined as `Step = Union[Function, Unix]`.

https://github.com/equinor/ert/blob/ac2ea6ecc0d7f8323414e0f3a46c8261f48d048b/ert3/config/_stages_config.py#L107

One usage of `step_from_key` that I've found is this: (not the **cast** to Stage step)

```python
    def get_stage(self) -> Step:
        """Return the stage used by the forward model in this
        experiment.

        Returns:
            str: The name of the stage.
        """
        stage = self._stages_config.step_from_key(
            self._ensemble_config.forward_model.stage
        )
        # The stage has already been validated to exist:
        return cast(Step, stage)
```

This is done in `test_evaluator.py`:

```python
    step_builder = (
        create_step_builder()
        .set_name(f"{stage.name}-only_step")
        .set_type("function" if isinstance(stage, ert3.config.Function) else "unix")
    )
```

Note the check whether stage is a function or not.

**Comment by BjarneHerland** [comment]
Shooting from hip: Using None is to avoid raising `StopIteration` when calling next() , no?

https://docs.python.org/3.8/library/functions.html#next

Hence, when calling `step_from_key()` one can check for None instead of catching `StopIteration`, but one or the other is necessary in case no step is associated with the given key.

I guess an alternative might be `def step_from_key(self, key: str) -> Optional[Step, None]` but a check after calling `step_from_key()` still seems necessary?

**Comment by BjarneHerland** [comment]
Furthermore, it looks (although I might be wrong - too little coffee today) like the implementation of `step_from_key()` returns only the first matching Step? Then another approach could be to mimic the dict-semantics and raise `KeyError` if no match was found.

Alternatively, if `StagesConfig` is supposed to hold more than one Step matching any key, I would make this an iterator/generator, requiring the caller to iterate or check for len().

**Comment by dafeda** [comment]
`step_from_key` is no more.
