### ISSUE TITLE
Starting multiple ERT with ensemble evaluator will eventually exhaust port range

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#2852]
**Describe the bug**
A user started 9 ERT instances and got an `Address already in use` error from the system.

**To Reproduce**
Start ERT 9 times (on an RGS node)

**Expected behavior**
This should work fine.

**Enviromment**
 - OS: RHEL7
 - ERT/Komodo Release: 2022.01.01
 - Python version: 3.6
 - Remote/HPC execution involved: yes

**Comment by sondreso** [comment]
The underlying problem of exhausting the valid port range by opening a lot of ert instances is difficult to circumvent. The user can have 2 RGS sessions on different node, and hence get twice the capacity when it comes to available ports. However, the use case here should rather be addressed by running experiments in sequence, in order to not occupy to much resources on the compute cluster at the same time. This can be done by automating the experiements using the CLI interface of ert in a script. 

We should however look into why this error message happened already on 9 instances, as there are 20 ports available. So the port range should not have been exhausted this early.

**Comment by lars-petter-hauge** [comment]
I tried to reproduce this issue and created a small script that ran the poly case n times (introducing a small sleep in the poly_eval.py). 

Running for 20 cases simultaneously works as expected. Getting `No available ports in range range(51820, 51841).` when trying 21+ cases. Redid multiple times for a consistent result.

This was running locally on my computer though.

I observed that ert for some reason did not shut down properly, and I ended up having hanging processes of ert instances. This resulted in ports being used and eventually merely a `python -c "from ert_shared.port_handle import find_available_ports; print(find_available_ports())"` would induce the `no available ports` error. This occurred while I was making the script and testing it out, so I don't know how to recreate the hanging ert process.. But it could be that the user was in a similar situation? Also, I suppose multiple users on the same node could result in ports being used.

I'll do a check on an rgs node though, to see if I get a different response.

**Comment by sondreso** [comment]
Great testing @lars-petter-hauge! I guess this works as expected then, and we can close this issue and rather open a new issue for not hanging when the exception is encountered?

**Comment by lars-petter-hauge** [comment]
Yeah, this looks to be working as expected and likely some specific scenario on the users side could lead to the error being shown before they have started ert 20 times.

I don't think it's that much of a normal case to open as many instances of ert, and besides, if it _really_ is something that is wanted (and not solvable by running the CLI sequentially instead), it would be possible to solve by specifying the port range:
```

  --port-range PORT_RANGE
                        Port range [a,b] to be used by the evaluator. Format: a-b
```
