### ISSUE TITLE
Issues related to std_scale_correlated_obs

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#287]
consider the same observation in multiple correlation groups, the scaling will  be overwritten. 
Possible solution
- only apply the scaling factor to the first key listed, and the rest used to calculate scaling values (without the results applied), (separate job?)

Multipler result is stored in the same spot as the MDA weights, overwriting the std_scale_correlated. 

Can only work with a complete observation key, not a subset. E.g. summary keys/GEN_DATA by report_step, or position in RFT data.

`enkf_main_std_scale_correlated_obs_JOB` in https://github.com/equinor/libres/blob/master/lib/enkf/enkf_main_jobs.cpp

**Comment by lahus2** [comment]
One more topic that came up during further discussions. Would it be possible to also have the job report the degrees of freedom for a group of observations, in addition to the scaling factor.

**Comment by oyvindeide** [comment]
Connected with: https://github.com/equinor/libres/issues/484

**Comment by oyvindeide** [comment]
1) Separating `enkf_obs_local_scale_std`, i.e the actual scaling from the scaling factor calculation in `enkf_obs_scale_correlated_std`
* This is pretty straight forward, not to many functions are calling this.

2) New (?) job to apply scaling factor to subset
* Applying the scaling factor to the first key seems a bit counter intuitive, probably better to supply two lists, one for calculation and one for application? Because the behavior is very different it would probably be a new job anyway.

3) Combine scaling factors
* What operation are we envisioning here? The option to change the update function, something like: `summary_obs_add_std_scale` and `summary_obs_multiply_std_scale`?

Combined it will be a pretty significant change to the current behavior, it _might_  be worth moving some of this functionality to the python layer?

**Comment by markusdregi** [comment]
I agree with 1 and 2. Let us execute those first, because that allows for testing the new job. 3 only limits using this together with the ES-MDA algorithm and that can wait for a second round ;) Step by step...

3 can potentially go much deeper into the code, so just ignore it for now and do whatever makes one and two easiest for you. If you prefer moving to Python that is fine, but it is also perfectly fine to just stick in C++ ;)
