### ISSUE TITLE
Provide better feedback/validation/error handling when a workflow job cannot be executed

### ISSUE THREAD

**Issue by ManInFez** [equinor/ert#2885]
Currently ERT only provides a warning i a job is not loaded correctly (executable not existing or no executable rights. ERT only crashes when you try to run the forward model. ERT should provide an error when jobs are not loaded correctly.

**Comment by rnyb** [comment]
Currently there's no useful info in the warning message printed out. An error message should preferable contain some information about which files are missing the executable or similar info to point the user in the right direction

**Comment by BjarneHerland** [comment]
@jondequinor is this relevant input for the ExperimentServer?

**Comment by eivindjahren** [comment]
This issue came up in the ert-users slack channel recently where a user spent a long time troubleshooting before realizing that the job did not have execute rights. This issue seems to align with the ongoing epic #2536 . Seemingly what needs to be done is to do our usual c to python refactoring of WorkflowJob and add better validation.
