### ISSUE TITLE
Investigate duplicate check in summary collector

### ISSUE THREAD

**Issue by TerryHannant** [equinor/ert#2899]
Preliminary profiling of retrieving Summary vectors via api found that  a check for duplicates performed at

https://github.com/equinor/ert/blob/main/ert_shared/libres_facade.py#L163

Can take longer to perform than reading data from dark storage
For example 200 realizations x 30 000 on RGS node:

- reading data from dark storage  - 2.0s
- checking for duplicates  - 2.7s

Thus this check is a heavy overhead when retrieving data via API.

Investigation needs to be done to see if the duplication check is needed or if it can be removed.

**Comment by oysteoh** [comment]
Relates to #2900

**Comment by BjarneHerland** [comment]
Modified code to avoid some redundancy and utilize the fact that the `DataFrame` returned from `SummaryCollector.loadAllSummaryData` already has a multi-index. These changes also handles #2900.

Benchmarking case with 200 realizations and summary-vectors 1000 elements long, meaning that each call to `gather_summary_data()` loads 200k values. Timing comes from `pytest-benchmark` on an RGS-machine with data mounted over NFS:

```
gather_summary_data, single vector (original) : 124,4ms
gather_summary_data, single vector (modified) :  94,4ms
```
giving ~25% improvement in total. Not much but worth the effort IMO.

Breaking down time usage shows that loading data takes ~49% of the time in modified code vs ~37% in original code

`load_all_summary_data:  46,5ms`

i.e. `checking for duplicates + pivoting` is ~48ms in modified code vs ~78ms in original code, meaning that the modified code **_after_** loading data spends about 61% of the time compared to original solution. No duplicates are found and removed in this dataset.

The time spent in modified code after loading is roughly 9-10% checking for duplicates and 90% pivoting, i.e. ~4ms checking and ~44ms pivoting (`unstack()` in fact, since the multi-index is kept intact). The corresponding split in original code is typically 40-60, i.e. checking for dups ~32ms and pivoting ~45ms in this example.

Most of improvement thus comes from checking for dups explicitly on index, then some from unstack'ing instead of full pivot.

Loading data can be broken down to

```
load_active_list :  0.7ms
load_time_map    :  8.1ms
load_summary_keys: 34.3ms
```
Hence there might be a potential for improving load-time by dissecting `load_summary_keys()`

### Remarks
- there is no test AFAICS which verifies that removing duplicates works
- if removing duplicates the code prints a warning - shuold probably be replaced with proper logging
- loading more than one summary-vector would have the same overhead checking for dups and pivoting
