### ISSUE TITLE
Seed is not logged to log-files nor terminal

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#309]
The seed is no longer logged to neither the terminal nor the log-files with the default log settings! That should change back...

**Comment by markusdregi** [comment]
This should be backported to `2.4` (the fix is probably in _libres_)

**Comment by markusdregi** [comment]
And, this is probably related to the never ending story of what level to log on (and where to log) before the configuration has been loaded.

**Comment by jondequinor** [comment]
I will defer logging of the seed until the configuration has been loaded, and log at INFO level, since the seed, after the sim is done, is logged using `res_log_info`.

But what seed is supposed to be logged? It looks to me that `SEED` is unused after loading, and that `RANDOM_SEED` is the one actually used.

**Comment by markusdregi** [comment]
It is indeed the RANDOM_SEED that should be logged. This will enable users to replicate an experiment in case something goes horribly wrong...
