### ISSUE TITLE
Use of multiprocessing in prefect.py

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#3135]
In prefect.py multiprocessing is used to start the prefect workflow. When canceling a workflow, a `signal.SIGINT` signal is sent that kills the process. This is problematic since the user may send that signal by pressing Ctrl-C which kills that process before the proper cancel procedure is invoked. While that gives the desired effect (an interrupt) it spits out a lot of exceptions in the console in the process.
(Related issues: #3099,  #3134)

We should look at alternatives to launch the workflow in the background and properly shut it down when needed.

**Comment by jondequinor** [comment]
Using `subprocess.Popen` is maybe the best course of action.

We could then do

```python
import subprocess
import signal

def preexec_function():
    # Ignore the SIGINT signal by setting the handler to the standard
    # signal handler SIG_IGN.
    signal.signal(signal.SIGINT, signal.SIG_IGN)

prefect = subprocess.Popen(
    ["prefect", …]
    preexec_fn = preexec_function
)
```

and send our own `SIGINT` for cancelling. There's probably a way of doing this for multiprocessing as well, but switching to `Popen` additionally solves the issue of proper encapsulation of the workflow manager in ert3. Currently there's a lot of shared memory between ert3 and prefect via multiprocessing pickling. This causes a host of problems, most notably it prevents us from using the `TestClient` from ERT storage due to its use of a singleton (which is not pickled).

Using `Popen` would force ert3 to interface with prefect by communicating, not sharing memory.

**Comment by oyvindeide** [comment]
Closing as ert3 related, and no prefect in current ert.
