### ISSUE TITLE
Create Experiment Server

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#3152]
**Motivation:**
The `BaseRunModel` (_BRM_) is a major pain-point in ERT currently, as it contains most of the logic for running and controlling an experiment, while the interface it exposes is vague, implicit and error prone. In addition, the current implementation, the Ensemble Evaluator (_EE_) starts and stops a websocket server multiple times per run, which is not the intended use of this technology, and also leads to weird synchronization handling in other parts of the code. 

The BRM also has a state which is hard to reason about, and is also not very collaborative—i.e. you need to poll fields to know the state over time.

There is also state for which no field exist: hooks and update code that may take hours to run, isn't at all observable.

**Approach:**
When implementing the EE, we had good experience with using a strangulation pattern for an evaluation. We could "wrap" the BRM and create a "LegacyExperiment", which follows an API that we define for an experiment.

For ERT3, an "ERT3Experiment" would implement the same API.

The EE also has a rudimentary state machine which could be extended for use by experiments. This promotes the EE from evaluating ensembles to running experiments.

**Behavior:** 
To avoid starting and stopping the server multiple times, an approach would be to implement a service (similar to how the storage works). The server is then always running, and the rest of the code can submit experiments and evaluations.

Different clients will probably have different needs for the granularity of events they want to receive (experiement only/ evaluation only), which we need to facilitate. This should be done with one connection, and extend the client-evaluator protocol to also include specification of what events the client want to subscribe to. 

The current code is also complicated by the fact that we have a dense mix of threads and async code. Most of the stuff going on in an experiment is IO-bound and trivially parallelizable, so asyncio should be the preferred way to run this code.

**Comment by sondreso** [comment]
See also: https://github.com/equinor/ert/issues/1250

**Comment by jondequinor** [comment]
This is a proposed high level component description of the experiment server system based on working on @sondreso's experiment server, as well as conversations with @BjarneHerland, @lars-petter-hauge (and ancient discussions around the "experiment authority"):

This document only describes the _legacy experiment_, but its API should be the same for an _ERT3 experiment_.

**Experiment server**

- Has a _registry_ containing list of experiments. A _client_ can query this registry. This registry will be used as a basis for a set of URLs so that a client can "subscribe" to different levels of information for different experiments, or for remote workers that wish to communicate with the experiment server:
Examples:
   - `ws://localhost:8000/client/experiment/0`
   - `ws://localhost:8000/client/experiment/0/ensemble/0` information about the first assimilation cycle for experiment 0
   - `ws://localhost:8000/client/experiments` yields a full list of experiments, as well as updates as they come
   - `ws://localhost:8000/remote/experiment/0/ensemble/0` for a remote worker sending information about the first ensemble in experiment 0.

These URLs will always be valid and always work, but semantics will be added for non-existent experiments and so on.


- The experiment server also has a _dispatcher_ which passes on _cloud events_ from  _remote_ traffic, i.e. cluster work, to an experiment. This dispatcher also broadcasts cloud events to clients, which implies it also does _batching_ of events.

This way, the server is reduced to mainly communication and defining a protocol for clients and remote workers. Its state is simply 1) clients connected, 2) remote workers connected, 3) experiments in the registry.

**Experiment**

- Has a _runner_ which runs the experiment. Can be started and cancelled via the _input bus_. Remote workers also communicate with the runner on the input bus via the experiment server.
- A _state machine_ keeps track of the state of the experiment. The runner provides the state machine with stimuli both from its local state and remote state, the latter interpreted from cloud events over the input bus. State changes produces cloud events on the _output bus_.

(The input bus could be a method call, if no threads are involved—only asyncio.)

The runner is essentially the `BaseRunModel` but with extra code that stimulates the state machine and responds to input.

**Ensemble**

The `LegacyEnsemble` can be largely unchanged. It will be started by the experiment runner, but will communicate with the experiment server as it does today.

**Comment by jondequinor** [comment]
The above design would implement the following sequence diagram:

```mermaid
sequenceDiagram
actor User
User ->> Server: Submit Experiment
Note right of Server: Setup event listener
Note right of Server: Create run() task
Server ->> Experiment: await run() task
Experiment ->> StateMachine: Stimuli (simulation start)
StateMachine -->> Server: StateChange (experiment start)
Server -> StateMachine: Retrieve snapshot
rect rgb(191, 223, 255)
Note right of User: Websockets event
Server --) User: Snapshot
end
Experiment ->> Evaluator: build and run
Evaluator ->> StateMachine: Stimuli (ensemble start)
Note right of Server: Put this StateChange in a batch
StateMachine -->> Server: StateChange (ensemble start)
Evaluator ->> Cluster: Start remote work
loop Until all realizations are complete
    rect rgb(191, 223, 255)
    note right of Server: Websockets event from the cluster
    Cluster --) Server: Job start|update|success
    end
    Server ->> StateMachine: Stimuli (job start|update|success)
    Note right of Server: Also batched
    StateMachine -->> Server: StateChange (Job start|update|success)
end
rect rgb(191, 223, 255)
note right of Server: Websockets event from the cluster
Cluster --) Server: Job success (final one)
end
Server ->> StateMachine: Stimuli (job success)
Note right of Server: Maybe not batched
StateMachine -->> Server: StateChange (Job success)
Server -> StateMachine: Retrieve snapshot
rect rgb(191, 223, 255)
Note right of User: Websockets event
Server --) User: Partial update
end
Evaluator ->> StateMachine: Stimuli (ensemble success)
Note right of Server: Put this StateChange in a batch
StateMachine -->> Server: StateChange (ensemble success)
Experiment ->> StateMachine: Stimuli (experiment success)
StateMachine -->> Server: StateChange (experiment success)
rect rgb(191, 223, 255)
Note right of User: Websockets event
Server --) User: Partial Update + End
end
```

Dotted: queues. Blue: websocket. All other is some sort of API.

**Comment by sondreso** [comment]
Very nice description! I think the choice of connecting to `ws://localhost:8000/client/experiment/0` to get events from an experiment and `ws://localhost:8000/client/experiment/0/ensemble/0` for events from an evaluation is something that can be discussed. Might be that we can have one websockets endpoint, and the client can specify which experiments/evaluations it want to get info about with control  messages instead.

**Comment by jondequinor** [comment]
Revised WIP

```mermaid
sequenceDiagram
actor User2
actor User1
User1 ->> Server: Submit Experiment
rect rgb(191, 223, 255)
User1 ->> Server: Connect
end
Server ->> Experiment: await run() task
Experiment ->> StateMachine: Stimuli (simulation start)
StateMachine ->> StateMachine: Transition to state(0,1)
Server ->> StateMachine: Retrieve full state
StateMachine ->> Server: state0
rect rgb(191, 223, 255)
Note right of User1: Websockets event
Server --) User1: state(0)
end
Experiment ->> Evaluator: Evaluate ensemble
Evaluator -->> Experiment: Stimuli (ensemble start)
Experiment ->> StateMachine: Stimuli (ensemble start)
StateMachine ->> StateMachine: Transition to state(0,2)
rect rgb(191, 223, 191)
User2 ->> Server: Connect
end
Server ->> StateMachine: Retrieve full state
StateMachine ->> Server: state(0)
rect rgb(191, 223, 191)
Note right of User2: Websockets event
Server --) User2: state(0)
end
Server ->> StateMachine: Retrieve update state
StateMachine ->> StateMachine: Transition to state(2,2)
StateMachine ->> Server: state(2)-state(0)
rect rgb(191, 223, 191)
Note right of User2: Websockets event
Server --) User2: state(2)-state(0)
end
rect rgb(191, 223, 255)
Note right of User1: Websockets event
Server --) User1: state(2)-state(0)
end
Evaluator ->> Cluster: Start remote work
loop Until all realizations are complete
    rect rgb(191, 223, 255)
    note right of Server: Websockets event from the cluster
    Cluster --) Server: Job start|update|success
    end
    Server ->> StateMachine: Stimuli (job start|update|success)
    StateMachine ->> StateMachine: Transition to state(x,y)
    opt Retrieve after time t - receive all transitions in aggregated form since last retrieval
        Server ->> StateMachine: Retrieve update state
        StateMachine ->> StateMachine: Transition to state(y,y)
        StateMachine ->> Server: state(y)-state(x)
        rect rgb(191, 223, 191)
        Note right of User2: Websockets event
        Server --) User2: state(y)-state(x)
        end
        rect rgb(191, 223, 255)
        Note right of User1: Websockets event
        Server --) User1: state(y)-state(x)
        end
    end
end
rect rgb(191, 223, 255)
note right of Server: Websockets event from the cluster
Cluster --) Server: Job success (final one)
end
Server ->> StateMachine: Stimuli (job success)
Note right of Server: Maybe not batched
StateMachine -->> Server: StateChange (Job success)
Server -> StateMachine: Retrieve snapshot
rect rgb(191, 223, 255)
Note right of User1: Websockets event
Server --) User1: Partial update
end
Evaluator ->> StateMachine: Stimuli (ensemble success)
Note right of Server: Put this StateChange in a batch
StateMachine -->> Server: StateChange (ensemble success)
Experiment ->> StateMachine: Stimuli (experiment success)
StateMachine -->> Server: StateChange (experiment success)
rect rgb(191, 223, 255)
Note right of User1: Websockets event
Server --) User1: Partial Update + End
end
```

**Comment by jondequinor** [comment]
I think the state _has_ to be updated constantly, because at some point the experiment will ask whether or not there is a sufficient amount of successful realizations to continue the experiment. This number cannot be dependent on circumstance.

**Comment by jondequinor** [comment]
This issue is too broad and has been split up in several issues. See #3437 where the design discussion should continue as well.
