### ISSUE TITLE
Pydantic statemachine (snapshot) might halt aioloop

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#3401]
For models that are sufficiently large and fast, i.e. 200 realisations and 30+ make/copy directory jobs early in the forward model, some batches in the evaluator event batcher may consist of ~12k events. On Rgs nodes, this takes more than 10 seconds to process, which blocks the aioloop for the entire duration. 

Blocking the evaluator aioloop is consistent with what is seen in one asset's logs: cluster web socket connections dying for no apparent reason, the evaluator's health check timing out (with a 10 seconds timeout) and intermittent traffic for clients connected to the server though the cluster is computing as full speed (thus traffic should be non-intermittent).

Pydantic is used by the statemachine to type the different constituents (jobs, realisations, etc) and it could be the source of the sluggishness. Alternatively, the recursive merge that is used to update the SM may also contribute.

After some investigation I found that `recursive_update` is the culprit.

**Comment by BjarneHerland** [comment]
#3408 is a simple idea originally voiced by @lars-petter-hauge and should prevent this issue from happening on our RGS-nodes.

It is, however, not robust in the sense that it hardcodes the size of batches, assuming that these batches are handled fast enough to not block the aioloop.

It might be possible to set size adaptively. The patch includes logging so that we can monitor timing and decide if further refinement is needed.
