### ISSUE TITLE
Benchmark fullstate vs delta state for GUI

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#3581]
Compare benchmarks from running a synthetic case (200 reals, 70 fast jobs):
- using the current implementation (delta states)
- using a new implementation of the underlying data model of GUI snapshot model using full state protobuf

**Comment by jondequinor** [comment]
This benchmark ran two programs meant to simulate how one particular asset's GUI model would be updated during times of most load (early in the forward model where folders are created/files are copied). The two programs differed as described above:
- the _current implementation_ uses deltas to update the GUI model which has a underlying tree model specifically made for the QT GUI
- the _protobuf implementation_ does not use deltas and the underlying data model is the protobuf objects themselves

Total time spent is more or less the same, but isolated, the protobuf `update_ensemble` method appears to be faster. This makes sense since this implementation uses the deserialized over-the-wire data as-is, whereas the current implementation has to be transformed.

| implementation | method  | per call (cumulative time / ncalls) |
| ------------- | ------------- | ------------- |
| protobuf | `update_ensemble` | **0.34** |
| current | `_add_partial_snapshot` + `prerender` | 0.31 + 0.20 = **0.51**  |

As load quiets down, for example when Eclipse is running for eight hours, `update_ensemble` will still use more resources each update, compared to a much lower number for the current implementation since deltas will decrease in size.

For example, when only one job is being updated for all realizations, `_add_partial_snapshot` consumes 10 times less cpu, compared to only three times less for `update_ensemble`.

On the other hand, the protobuf implementation is much more terse, and will probably make for a much simpler implementation of the _experiment server_ as the need for computing deltas goes away.

**Comment by xjules** [comment]
Let's increase the testing case for ca. 1000 realizations and 100s jobs.

**Comment by Blunde1** [comment]
Updated `pbuf_bench` branch to 1000 realizations and 100 jobs and ran `pytest --benchmark-max-time=10 --benchmark-cprofile=cumtime tests/ert_tests/gui/simulation/test_run_dialog.py::test_pbuf_full_state`

<img width="963" alt="image" src="https://user-images.githubusercontent.com/13650516/182330021-005888f2-466b-4fea-a1cb-e90dedbfd3cd.png">

**Comment by Blunde1** [comment]
Updated current implementation `bench_current_run_dialog_update` on [my own fork](https://github.com/Blunde1/ert/tree/bench_current_run_dialog_update) to 1000 realizations and 100 jobs

<img width="963" alt="image" src="https://user-images.githubusercontent.com/13650516/182362358-ca0e0419-4a1b-4063-919a-654537d5d3e3.png">

**Comment by Blunde1** [comment]
The relevant timings:

| implementation | method  | per call (cumulative time / ncalls) |
| ------------- | ------------- | ------------- |
| protobuf | `update_ensemble` | **3.26** |
| current | `_add_partial_snapshot` + `prerender` | 2.25 + 1.43 = **3.68**  |

**Comment by xjules** [comment]
Good job @Blunde1! I think the results render better statistics now, which suggests the Protobuf is the right way to go.
