### ISSUE TITLE
test example.ert using ert_tui

### ISSUE THREAD

**Issue by xclmj** [equinor/ert#372]
Hi, all,

I have successfully install the OPM and ERT in my computer. When I use the ert_tui to test example.ert by the command line ert_tui example.ert . I encounter the following problem as follows:

Abort called from: util_abort_signal (.../libecl/lib/util/util.c:4410)

Error message: Program received signal:11

#00 util_abort__(..) in .../libecl/lib/util/util_abort_gnu.c:173
#1 ????
#2 ert_run_context_get_mode(..) in .../libres/lib/enkf/ert_run_context.cpp:336
#3 enkf_main_init_run(..) in .../libres/lib/enkf/enkf_main.cpp:1606
#4 enkf_main_run_simple_step(..) in .../libres/lib/enkf/enkf_main.cpp:1654
#5 enkf_main_run_smoother(..) in .../libres/lib/enkf/enkf_main.cpp:1664
#6 _Z21enkf_tui_run_smootherPv(..) in ???
#7 menu_run(..) in ???
#8 _Z17enkf_tui_run_menuPv(..) in ???
#9 menu_run(..) in ???
#10 _Z18enkf_tui_main_menuPv(..) in ???
#11 main(..) in ???
#12 __libc_start_main(..) in /build/glibc-77giwP/glibc-2.24/csu/../csu/libc-start.c:325
#13 _start(..) in ???

Do you know how to solve this problem?

best regard

**Comment by markusdregi** [comment]
Hi Cong Xiao,

Did the `util_abort` not also come with a message?

Did you remember to change the name of the simulator in the `example.ert` to use `flow` instead of `ecl100`? Did you remember to configure the `flow` job as described in _libres_?

If you remembered both of those things, I would suggest you do the following:
- Test that you manage to run the `test-data/local/poly_example/poly.ert` case. It requires no setup besides correct installation. I would expect this to work, as otherwise your installation is broken.

- Try to comment out the line:

```
OBS_CONFIG observations/observations.txt
```

by putting `--` in front of it and run an `Ensemble experiment`. If this fails, check if all forward models succeeded. This is most easily done by running the case via the GUI and pressing the `Details` button. Verify that all forward models turned green.

Let me know how it goes and I'll assist you further.

**Comment by xclmj** [comment]
Thanks for your kind help.  When I test the snake oil example,  by using a GUI: ert gui snake_oil.ert, (frankly speaking, I do not give any corrections for snake_oil.ert file. Actually, I cannot find anything about installing flow job in this snake_oil.ert file), surprisingly,  the model can be ran successfully.   These two cases make me confused. 

best regard

**Comment by markusdregi** [comment]
Alright, it goes as follows:

- `poly.ert`: Does a simple linear regression and requires no additional setup besides basic installation. Check out the `README` in the folder for more information. This is a very good base for testing that your installation works. It also highlight some of the features of _ERT_ in the simplest manner possible.

- `snake_oil.ert`: Also does not require any configuration besides a basic installation. This is because this setup never executes any reservoar simulator, but instead mocks some results that are dumped in the run path.

- `example.ert`: Runs a reservoar simulation and hence requires the configured simulator to be installed.

If the first two works, while the last one does not. I'm expecting that it is indeed the simulator configuration that went wrong. There is no documentation of this in the specific case, but you should revisit the README of _libres_; in particular section `6.2.1. Eclipse/flow configuration`. You need to configure your `flow` simulator if _ERT_ is to be able to execute it. In addition you have to change the `example.ert` so that it runs `flow` instead of `ecl100` in the forward model...

Cheers

**Comment by xclmj** [comment]
I have re-installed the ert and modify the flow job.  I can successfully run the example case.  Thanks for your kind help.

best regard

**Comment by markusdregi** [comment]
Happy to help 👍
