### ISSUE TITLE
Ensure test coverage of callbacks

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#3825]
To be able to replace the OK [callback](https://github.com/equinor/ert/blob/fe178fd04430053921fc578b5935b5ff11896657/src/clib/lib/enkf/enkf_state.cpp#L503) we need to make sure it is properly tested.

The callback is responsible to load three main things:

1. Parameters defined with `FORWARD_INIT`, i.e. parameters that are not sampled by `ert`, but read from file after the forward model has completed (`GEN_KW`, `FIELD` and `SURFACE`, and possibly also `GEN_PARAM`).
1. Loading summary data, this amounts to checking if the `ECLBASE` file is present in the run path (if summary is defined) and loading the data. There is a lot of complexity involved in checking if the time map is in sync. We need to test this behavior, but it is probably covered enough. We would like this behavior to change into saving the time map for each realization.
1. Loading `GEN_DATA`, here we can load both binary and ascii data, but should investigate if both are being used, suspect only ascii is being used, if so this can be simplified.

Known tests:
`test_load_forward_model.py`
`test_parameter_sample_types.py`

Edit: definition of done: reviewed test coverage to make sure we are ready to reimplement.

**Comment by frode-aarstad** [comment]
The test coverage seems decent.
1. All four parameter types are covered in `test_parameter_sample_types.py`. Will add an explicit check for the internalized parameters.
2. There are tests in `test_load_forward_model.py` that test if the loading of summary data succeeds and tests for faulty time_map
3. It seems like no one uses the binary versions of the input format. Ran a query on the FMU logs in azure and there were no hits since 1.1.2022. So I guess it is safe to just focus on the ASCII part. There are tests for loading summary data in `test_gen_data.py` and `test_gen_data_collector.py` using the data from snake oil.
