### ISSUE TITLE
Include link to documentation in ERT gui -> Help

### ISSUE THREAD

**Issue by eivindsm** [equinor/ert#390]
Feedback from users suggest that the documentation page is difficult to find. I propose to include a  link in the GUI under Help. Currently ERT->Help consist of About. Probably not what most users have in mind when they seek help :) 

I suggest to include the links: 
Manual: http://sib-docs.equinor.com/docs/ert/2.5/manual.html  consistent URL and ERT version) 
Wiki: https://wiki.equinor.com/wiki/index.php/ERT_main_page

**Comment by markusdregi** [comment]
This should probably be optional when installing, as many of these resources does not make sense externally.

**Comment by markusdregi** [comment]
Could also add links to slack, yammer, GitHub and S@E.

**Comment by sondreso** [comment]
I could use some input on the best way to implement the difference in the links used between the internal and open version. So far it fetches a yaml file with links from the resource folder. Hence, the resource file itself can be overwritten in the install process, but this feels hacky. Another idea is to use a config file to specify the file with help links, and default to the file in the resource folder in case nothing is specified. But which config file should this file be a part of? The SITE_CONFIG is an option, would prefer to leave configuration of the gui and libres separate.

**Comment by markusdregi** [comment]
Today there is only one configuration source of ERT and it configures all from model, numerical behavior to favorite color in the GUI (or at least close ;)). In my opinion the current configuration should be purely behavioral and then we would later possibly introduce an appearance configuration (not in any way affecting the results of the run) that could configure this. Since the configuration is under such heavy refactoring as we speak I suggest we not introduce new elements to it; especially when they are not defining behavior (as you also point out).

I think a yaml solution will be good enough for now and then we can address this further in the future when the configuration itself has stabilized a bit 👍

**Comment by sondreso** [comment]
Agreed! Then I will just include the github link for now
