### ISSUE TITLE
ConfigContent.py does not correctly handles analysis SET_VAR 

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4028]
There is something buggy about  the following:
``` python 
user_config_content_as_dict = user_config_content.as_dict()
user_config_content_as_dict_simplified = {
    key: value[0][0] if len(value[0]) == 1 else value[0]
    for key, value in user_config_content_as_dict.items()
}
```

I think this logic should be part of `ConfigContent` and not added to `ResConfig` also the simplified dictionary does not account for keys that can have multiple elements like the following:

```
QUEUE_OPTION SLURM MAX_RUNNING 50
QUEUE_OPTION SLURM SBATCH /path/to/sbatch
QUEUE_OPTION SLURM SQUEUE /path/to/squeue
ANALYSIS_SET_VAR    STD_ENKF     ENKF_NCOMP    2
ANALYSIS_SET_VAR    ENKF_HIGH_TRUNCATION     ENKF_TRUNCATION    0.99
```

The following test should be able to pass:

```python 
def test_config_content_as_dict(tmpdir):
    with tmpdir.as_cwd():
        conf = ConfigParser()
        schema_item = conf.add("KEY_VALUE", False)
        schema_item.iset_type(0, ContentTypeEnum.CONFIG_INT)

        schema_item = conf.add("KEY", False)
        schema_item.iset_type(2, ContentTypeEnum.CONFIG_INT)

        with open("config", "w") as fileH:
            fileH.write("KEY_VALUE 42\n")
            fileH.write("KEY VALUE1 VALUE1 100\n")
            fileH.write("KEY VALUE2 VALUE2 200\n")
        content = conf.parse("config")
        content_as_dict = content.as_dict()
        user_config_content_as_dict_simplified = {
            key: value[0][0] if len(value[0]) == 1 else value[0]
            for key, value in content_as_dict.items()
        }
        assert user_config_content_as_dict_simplified == {'KEY': [['VALUE1', 'VALUE1', 100], ['VALUE2', 'VALUE2', 200]], 'KEY_VALUE': 42}
```

**Comment by valentin-krasontovitsch** [comment]
first of all, mea culpa for making this half-baked solution, and I'm sorry.

after discussing a bit with Andreas, we think that only dedelisting the keys that have simple single values and leaving other keys alone is perhaps the way to go and probably will make Øystein's test pass.

also, thank you Eivind for pointing out and reminding us of the expected behaviour for those simple cases - that means that when dedelisting, we should use the index -1 rather than 0 for (I think) the first list access.

While your example of instantiating ecl config admittedly is yummy and elegant, I still wanna use the `to_dict` method of config content, so i'm gonna try to stick with that, if you don't mind : )

**Comment by eivindjahren** [comment]
> Changing the offending code to the following will make the test pass:
> 
> ```python
> user_config_content_as_dict_simplified = {
>             key: value[0][0] if len(value[0]) == 1 else value
>             for key, value in content_as_dict.items()
>         }
> ```
> 
> I am unsure how to proceed though, since:
> 
> * Where exactly should this codesnippet be moved?
> * The elegant code proposed by @eivindjahren will only cover the three cases mentioned, and not the example found in this issue. Are the more keywords we should cover?
> * Extracting this from EclConfig decouples the grid, data and refcase files from the configuration set.

My proposal assumed that we would have to special case a lot of different keywords when it comes from config content. Then once there is one code path, we can try to handle it in a generic way.

**Comment by valentin-krasontovitsch** [comment]
I suggest that you can EITHER

- use eivind's proposal of initiating ecl config, which means that you can remove the questionable "simplified config content dict" code snippet, and this whole problem just goes :dash:, OR

- disregard eivind's proposal and keep the way of initiating ecl config that we have at the moment
- move the code snippet that produces that simplified dict into the python config content class, which will also make it easier to test it
- use the test that Øystein proposed to make sure that the simplified dict behaves as expected (basically it will only do something with the simple config options)
- add another test case, where a simple config option is used twice in the same file, following Øyvind's example something like
```
    fileH.write("KEY_VALUE 42\n")
    fileH.write("KEY_VALUE 15\n")
```
and check that the last value is used.

one reason why i wouldn't worry too much about initing ecl config is that i'm currently trying to remove it altogether :innocent:

> Extracting this from EclConfig decouples the grid, data and refcase files from the configuration set.

I'm not sure I follow here - extracting what from ecl config?

During a quick look at this later on today with Eivind, he actually pointed out something that might be funky about my approach of simplifying the dict - namely the case of some keyword taking variable number of arguments. say a keyword accepts one value or two values and can be supplied several times simultaneously, doing different things (do we have anything like that, because it sounds very sane).
then having something like this in the config file
```
SANE_KEY OK
SANE_KEY DO SOMETHING
```
would result in a `item = content_as_dict["SANE_KEY"]` looking like this:
```
[ [ "OK" ], [ "DO", "SOMETHING" ] ]
```
or if the two lines in the config file are interchanged, we suddenly have
```
[ [ "DO", "SOMETHING" ], [ "OK" ] ]
```
and then we can have `len(item[0])` being either 1 or 2 :grimacing:

so i'm hoping this is not something that our config options allow, but maybe just to be on the safe side we should just send the whole simplified config content dict to my uncle's farm upstate... and wait for the refactoring that Eivind mentions instead of breaking our heads now, just because i wanted to use the `as_dict` method : ) and i of course again apologize for causing all these discussions...

**Comment by eivindjahren** [comment]
There is another advantage to the codesnippet I sent and that is that it uses `getValue` which everything else also uses to determine "what is the value of a keyword that should have just one value".

**Comment by valentin-krasontovitsch** [comment]
now you're just advocating consistency, which I find highly overrated - all methods have a right to be used equally ; )
