### ISSUE TITLE
Tools should not create QAction on its own

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#422]
The principle of least knowledge requires us to refactor the `ert.gui.tools.Tool` class to take a `QAction` instead of instantiating it:

https://github.com/equinor/ert/blob/bf6d58c0eb3286244fd6393c754e1746904b88ee/src/ert/gui/tools/tool.py#L21

This also has the benefit of easing the testing of any derived tools, simply because an inert `QAction` can be passed during initialization, instead of the concrete `QAction`, which currently requires a `QIcon`, which in turn requires a `QPixmap`, which will `abort` if there's no underlying running gui application.

**Comment by eivindjahren** [comment]
Currently the problem with attempting to this is that the QAction is used to disable the export tool when the export job is not available:

https://github.com/equinor/ert/blob/7281a9340f7d31a1835b11af849d98740bdfa2de/src/ert/gui/tools/export/export_tool.py#L31

That the export can be disabled because a job is not installed seems like it should be tackled first.

**Comment by eivindjahren** [comment]
While this is no longer blocked, the test for the exporter tool is now implemented in a different way, so there is no need for this refactoring.

If anyone wishes to create a more isolated test of the exporter tool, this refactoring is ofc a good start.
