### ISSUE TITLE
CLI basic monitoring

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#424]
The CLI should give some basic monitoring of how many forward models are running, waiting etc.

**Comment by jondequinor** [comment]
https://github.com/equinor/ert/issues/434 could be fixed as a part of this.

The CLI should read both `jobs.json` and `status.json` the same way as the GUI does.

**Comment by jondequinor** [comment]
I've created an implementation of this using `\r`, and it works somewhat _ok_. See this screenshot: ![Screenshot from 2019-10-17 14-36-36.png](https://images.zenhubusercontent.com/5d42cf5a3dd26100017e956b/13bdc7c1-b0d1-40c2-ac1c-a1304e40548d)

However, since the simulation (i.e. libres in general, fms, custom fms, workflows, etc) can produce arbitrary data on `stdout`, iteratively printing something that relies on `\r` could produce a lot of noise in the terminal.

We have two alternatives, as I see it:
- Sequentially printing the monitor output. Then monitor output would be interleaved with the output from the simulation. Works, but is maybe not the best way to present state and progress.
- Accept a `--monitor` argument that, when used, pipes the simulation `stdout` to file. This would leave only the monitoring output on `stdout`.
