### ISSUE TITLE
Revise documentation on user made forward models

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#431]
Revise and try to improve section on how users can make and install their own forward models. Should include hints towards how error handing should be done and more.

**Comment by lars-petter-hauge** [comment]
Does this entail that we should provide some guidelines/recommendations as to how to write those jobs (e.g. logging, capture throws, argsparse)?

We should probably be a bit constraint so that we don't write redundant information, and rather make extensive use of online content, and providing some minor examples.

**Comment by markusdregi** [comment]
Yes and yes ;)

**Comment by markusdregi** [comment]
But more importantly, we should describe the behavior of the job description files.

**Comment by oysteoh** [comment]
question @markusdregi @lars-petter-hauge :

quite extensive doc at this location http://sib-docs.equinor.com/docs/ert/getting_started/configuration/poly_new/guide.html?highlight=poly 

Any way of dealing with this at the same page / link instead of copy / paste and make the text slightly different - making more stuff for us to maintain? Does much lack in this page that needs to be documented in a "user made forward model" section

**Comment by lars-petter-hauge** [comment]
I agree, the part from http://sib-docs.equinor.com/docs/ert/getting_started/configuration/poly_new/guide.html?highlight=poly#create-script and onwards specifically describes which files to create, what content should be put in them and how they are related. Together with what we alread have in http://sib-docs.equinor.com/docs/ert/reference/configuration/forward_model.html?highlight=forward%20models#configuring-your-own-jobs I think we should be satisfied with information related to the "how"-ness. There should probably be a link between them though (maybe even both ways?)

**Comment by markusdregi** [comment]
The referred documentation seems to only cover `SIMULATION_JOB`. We should probably cover the `FORWARD_MODEL` keyword as well, as that is currently the most used one. And then we need to explain among others the `ARGLIST` keyword

**Comment by oysteoh** [comment]
> The referred documentation seems to only cover `SIMULATION_JOB`. We should probably cover the `FORWARD_MODEL` keyword as well, as that is currently the most used one. And then we need to explain among others the `ARGLIST` keyword

Yes, we should. And - is this covered good enough at the place @lars-petter-hauge refers to ( https://github.com/equinor/ert/blob/master/docs/rst/manual/reference/configuration/forward_model.rst#configuring-your-own-jobs) ?

**Comment by markusdregi** [comment]
I missed that one 👍
