### ISSUE TITLE
Drop dependency on ForwardModel[Job]Status in libres from ERT

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#434]
**Existing behaviour:**
ERT depends on `ForwardModel[Job]Status` in `libres` to render status/detailed status from the union of `jobs.json` and `status.json`.

`libres`'s `job_dispatch` also depend on `ForwardModel[Job]Status` to initially read `jobs.json` and later continuously update `status.json`.

**Discussion:**
Except from [de]serialization,  both classes`ForwardModelStatus` and `ForwardModelJobStatus` are without behaviour, and should be plain old data—i.e. dicts—if they are to be shared between the two projects. Or, if both `jobs.json` and `status.json` are sufficiently documented in `libres` such that it serves as the contract between ERT and `libres`, ERT can be decoupled from `libres` with regards to `ForwardModel[Job]Status`.

This decoupling would allow the GUI to change independently of `libres` for any change in how `jobs.json` and `status.json` is read.

It would also make any code reading and writing to these JSON files implementation details.

**Conclusion:**
We should introduce code in ERT to read `jobs.json` and `status.json` that is independent of `libres`.

**Comment by jondequinor** [comment]
Note that the internalization of `jobs.json` and `status.json` in https://github.com/equinor/libres/pull/653 has already been transitioned to a anonymous POD, so this issue is not dependent on that pull request.

**Comment by markusdregi** [comment]
Thanks for raising this discussion :+1: 

I would rather argue that the fact that we are running the simulations on a shared file system is an implementation detail that should not be seen in ERT. I would argue that instead of moving the functionality to read the `status` files into _ERT_ we should move the initialization the of `ForwardModel[Job]Status` status completely into _libres_ and let the queue manager have a way of telling us the status of things.

In the future we cannot rely on having access to the same disks, so making even stronger assumptions about this seems unfortunate...

**Comment by jondequinor** [comment]
Great!

Then we should apply the principle inversion of control to the UI, which now decides on its own a) when and where to read jobs/statuses, and b) when and how to update the UI. In QT, this is idiomatically done using a `QAbstractListModel` or, i.e., the MVC-pattern.

After this refactor, the UI is `QEvent` driven using a concrete `QAbstractListModel` implementation that should vary on where the events are sourced. If the events are sourced from enkfs storage, the concrete implementation is an e.g. `FileStatusListModel`.

**Comment by jondequinor** [comment]
This is going to be a permanent feature of the ERT legacy. I.e. it will be nuked after migrating to the new Ensemble Evaluator.
