### ISSUE TITLE
Indicate that Duration of job can be hovered to get start/end time

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#4372]
Hovering the Duration will show start time, it is not obvious for the user that this is a feature

<img width="1329" alt="Screenshot 2022-11-23 at 10 40 05" src="https://user-images.githubusercontent.com/26920711/203514464-dd037225-48e6-4cde-a189-9acdfb9b6c6c.png">

**Comment by jonathan-eq** [comment]
Attempted this, but it seems like we have to create a custom delegate for drawing the table.
It kinda worked by setting font underline in snapshot.py, but it was not that intuitive with a straight line instead of a dotted one.
Also tried setting border-bottom on a stylesheet on QTableView, but that rendered an underline under the cell; not under the text.

**Comment by oyvindeide** [comment]
Think I will close this as it was attempted, but not trivial, and we would like to do a larger rewrite.
