### ISSUE TITLE
Investigate Config Key warnings

### ISSUE THREAD

**Issue by DanSava** [equinor/ert#4399]
Looking at the console log for the HM-Tutorial I noticed the following warnings:

``` 
res.config - WARNING - ** Warning keyword: LOG_FILE not recognized when parsing: hm_analysis.ert ---
res.config - WARNING - ** Warning keyword: LSF_QUEUE not recognized when parsing: hm_analysis.ert ---
res.config - WARNING - ** Warning keyword: PORTABLE_EXE not recognized when parsing:
```

It might be wise to investigate why we are seeing these warnings and maybe are not handling these keys properly.

**Comment by andreas-el** [comment]
### LSF_QUEUE
Is a valid keyword / option for the QUEUE_OPTION
Ref.
https://fmu-docs.equinor.com/docs/ert/reference/configuration/keywords.html#lsf-queue

### PORTABLE_EXE
Deprecated keyword was removed in recent commit:
```
Simplify model config
commit 1a2dd8600597fb664da9e406e2d783e0b94d4b1d
Date:   Wed Nov 9 21:07:31 2022 +0100
```

The portable keyword was deprecated back in 2021.
```
Deprecate PORTABLE_EXE
commit 29dbff39d9a68710e6254457c576504cc9910ffa
Date:   Mon Jun 14 11:12:20 2021 +0200
```
The `PORTABLE_EXE` and `EXECUTABLE` keywords have been aliases for a while it seems.
The more recent Drogon datasets use `EXECUTABLE` instead of `PORTABLE_EXE`
Only in the Reek data is this still present.

### LOG_FILE
Was used to specify output log file. Currently ignored.
Ref.
https://fmu-docs.equinor.com/docs/ert/reference/configuration/keywords.html#log-file
