### ISSUE TITLE
Bug resolving CONFIG_PATH

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#4733]
There is a bug resolving `<CONFIG_FILE>`  in some configurations.

![Image](https://user-images.githubusercontent.com/4184190/214872911-eb095937-6eba-4fb1-897c-210c75cc9797.png)

**Comment by valentin-krasontovitsch** [comment]
it looks like the problem is the second parsing run of the config, done by the migration suggester - i could trigger it with the following minimal config file `snake_oil_min.ert` placed in `local-data/snake_oil`:

```
NUM_REALIZATIONS 25
GEN_KW SNAKE_OIL_PARAM <CONFIG_PATH>/templates/snake_oil_template.txt snake_oil_params.txt parameters/snake_oil_parameters.txt
```

by running (line breaks and indentation added for readability)

```
$ cd test-data/snake_oil
$ ert test_run snake_oil_min.ert
Error(s) in configuration file snake_oil_min.ert: \
  ['Can not find entry <CONFIG_PATH>/templates/snake_oil_template.txt \
  in /home/val/code/equinor/ert/test-data/snake_oil ']
```

but the attached patch fixes it. too tired to add tests and make a proper PR now though.

[suggestion-parser.patch.txt](https://github.com/equinor/ert/files/10513725/suggestion-parser.patch.txt)

**Comment by eivindjahren** [comment]
Nice find @valentin-krasontovitsch I am fixing it.
