### ISSUE TITLE
Analysis module not found message says "Error(s) in configuration file:None"

### ISSUE THREAD

**Issue by eivindjahren** [equinor/ert#4842]

**Comment by oysteoh** [comment]
Is it possible to also alter the message slightly in this PR? It is describing perfectly fine what is wrong, but i would like it to be more clear that `observations` is a file or folder - does that make sense? 
Instead of  
`Error(s) in configuration file poly.ert: ['Cannot find file or directory observations in /datadisk/repos/ert/test-data/poly_example ']` 

i.e
`Error(s) in configuration file poly.ert: ['Cannot find file or directory "observations" in path "/datadisk/repos/ert/test-data/poly_example"']` 


This is just nitpicking of course....

**Comment by DanSava** [comment]
How can I reproduce the error:

```
Error(s) in configuration file poly.ert: ['Cannot find file or directory observations in /datadisk/repos/ert/test-data/poly_example ']
```

**Comment by eivindjahren** [comment]
The error will happen if you are trying to copy a module that does not exist and set a variable for a module that does not exist. It might be that ConfigValidationError has a bug where it generates the wrong message.

**Comment by oysteoh** [comment]
> How can I reproduce the error:
> 
> ```
> Error(s) in configuration file poly.ert: ['Cannot find file or directory observations in /datadisk/repos/ert/test-data/poly_example ']
> ```

Just removed the observation-file and then ran the `poly.ert`  config
