### ISSUE TITLE
GEN_KW enhancement

### ISSUE THREAD

**Issue by rnyb** [equinor/ert#4907]
**Is your feature request related to a problem? Please describe.**

The GEN_KW keyword takes 3 arguments, however we often only need the 3rd argument (uncertainty distribution file) and the other two are just included because they are required.

`GEN_KW  GLOBVAR  ../input/templates/.dummy.tmpl   .dummy.yml   ../input/distributions/global_variables.dist`

**Describe the solution you'd like**

I would like either
1) GEN_KW to work with only one argument, so that if only one argument is given ERT will interpret that as the dist file
`GEN_KW  GLOBVAR   ../input/distributions/global_variables.dist`
OR
2) to have a new keyword, let's say DISTTRIBUTIONS, which only takes dist file as argument
`DISTRIBUTIONS  GLOBVAR    ../input/distributions/global_variables.dist`

**Comment by oyvindeide** [comment]
Sorry to answer your question with another question, but my question is this: What is the ideal use for this parameter?

I know there are some conventions around it, for example related to `DESIGN_KW`, however in the future, we would like to incorporate sensitivity into ert, and maybe adopt some of the functionality of `DESIGN_KW` to simplify the whole process. So if we disregard the current workarounds, how can we simplify the whole process, from start to finish? It could be adding a list of files to do replacements in for example, instead of a single one as is done now. It could be to remove it, and just put all the values in `parameters.`, but I think the latter use case is a workaround and maybe we can improve this functionality instead, and render that obsolete. What do you think?

**Comment by rnyb** [comment]
Yes, I agree that the optimal solution will be to redesign it entirely. However, this may require a longer process of brainstorming and iterations? So maybe it could still be beneficial to have the quick short term improvement implemented while waiting for the more long term solution?

**Comment by sago64** [comment]
To answer to your Q: This parameter GLOBVAR contains most of input parameters more or less. (not only 1 but can be 1000). Then we add to this the eclipse parameters (scalar). But in this specific example,  the usage here is related to the APS updates in ERT. It is a workaround that allows us to improve the match (Roger can correct me there?) so has nothing to do with sensitivity.. Probably would require a session to explain but here some comments you can follow in our example drogon_ahm file. (it basically allow to mix updates and hard input from design). 
![image](https://user-images.githubusercontent.com/55280570/224293029-019685bc-4622-4258-879b-2f7ac07f8900.png)
