### ISSUE TITLE
Improve ERTs outlier detection such that realizations considered outliers are removed from the response matrix

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#4948]
A user has reported that when they run assisted history match the analysis fails because all the parameters end up as NAN. The input to the algorithm is seemingly ok.

**Comment by dafeda** [comment]
Seems like the responses contain redundant information which causes the `S.T@S + Identity(N)` to be such that eigen produces zero eigenvalues. 

This ends up in infs since we by default use exact inversion and no truncation is applied.
Users have been asked to try using `SUBSPACE_EXACT_R` with a bit of truncation instead as this should get rid of the eigenvalues that are zero.

We need a better way to handle these things.
We changed the default to exact inversion about a year ago, which might not have been a good idea.
One possible solution is to calculate the minimum eigenvalue and switch to exact_R if its zero-ish.
This needs discussing.

**Comment by dafeda** [comment]
Here's a minimal example that yields nans.
AFAIK, our current outlier detection does not remove realizations that are "outliers".
I think this needs to be done before calculating distance between mean response and observation and deciding whether to include observation or not.


```python
import numpy as np
import iterative_ensemble_smoother as ies

rng = np.random.default_rng()
response_ensemble = np.array([[1, 1, 1e19], 
                              [1, 10, 100]])
noise = rng.normal(size=(2, 3))
param_ensemble = np.array([[1, 2, 3]])
obs_error = np.array([1, 2])
obs_value = np.array([10, 20])
ensemble_size = response_ensemble.shape[1]
Y = (response_ensemble - response_ensemble.mean(axis=1, keepdims=True)) / np.sqrt(ensemble_size - 1)
C = Y.T @ Y + np.identity(ensemble_size)
np.linalg.cond(C)
ies.ensemble_smoother_update_step(response_ensemble, param_ensemble, obs_error, obs_value, noise=noise)
```

**Comment by dafeda** [comment]
There's a test in `iterative_ensemble_smoother` that makes sure `SIES` provides reasonable error when large reponses are present:

https://github.com/equinor/iterative_ensemble_smoother/blob/640de4585ad27a04e5f46a282577dd00bd4481ce/tests/test_sies.py#L183-L229

I tried writing a similar test for ES-MDA but it does not fail. I think this is because the implementation of ES-MDA has changed to that of Emerick which handles these things differently. The SIES implementation is still based on the 2019 paper by Evensen.

**Comment by dafeda** [comment]
Closing because new implementation based on Emericks paper seems to not crash when there are "outlier" responses.
Will not implement "outlier" detection for responses because it is not clear what an outlier in this context is.
See this Slack post for some details: https://equinor.slack.com/archives/CDPJULWR4/p1718851372423449
