### ISSUE TITLE
Default case

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#4964]
There are some problems that need to be fixed / discussed:
- When starting from clean storage the "Current case" dropdown in empty. Used to contain "default". 
- After running ES the new case is not in the dropdown for plotting and the new case has its name derived from default (ie: default_smoother_update) even though I have created a new case and set it as current case

**Comment by pinkwah** [comment]
So there are several aspects to this:
1. I think this is due to something I overlooked. There needs to be a `New case` and not an empty dropdown.
2. The Qt plotter does this for some reason:
  https://github.com/equinor/ert/blob/7bdf7d360664e059c503870073c5a88c187ed441/src/ert/gui/tools/plot/plot_api.py#L71-L78
  I don't really know why but I think if we fix this we'll have all the cases.

**Comment by dafeda** [comment]
This PR fixes this (in part at least): https://github.com/equinor/ert/pull/4978

**Comment by oyvindeide** [comment]
Default case has been reinstated. Will reconsider default case once we merge the feature branch.
