### ISSUE TITLE
Support MAX_RUNTIME in Torque driver

### ISSUE THREAD

**Issue by berland** [equinor/ert#5121]
**Is your feature request related to a problem? Please describe.**
The Torque driver does not support the option MAX_RUNTIME that LSF and Slurm supports

**Describe the solution you'd like**
The same feature as LSF

**Describe alternatives you've considered**
None

**Comment by kwinkunks** [comment]
See https://github.com/equinor/scout/issues/790

According to the docs:

> The driver allows the backend Torque system to be flaky, i.e. it may intermittently not respond and give error messages when submitting jobs or asking for job statuses. The timeout (in seconds) determines how long ERT will wait before it will give up. Applies to job submission (qsub) and job status queries (qstat). Default is 62 seconds.

> ERT will do exponential sleeps, starting at 2 seconds, and the provided timeout is a maximum. Let the timeout be sums of series like 2+4+8+16+32+64 in order to be explicit about the number of retries. Set to zero to disallow flakyness.

>::
> QUEUE_OPTION TORQUE TIMEOUT 126

Indeed, `TORQUE_TIMEOUT` is picked up from `TIMEOUT`, not `MAX_RUNTIME` (as for Slurm). This is then passed on as `driver->timeout` in `torque_driver.cpp` in the `torque_driver_submit_shell_job` function. 

https://github.com/equinor/ert/blob/main/src/clib/lib/include/ert/job_queue/torque_driver.hpp#L21

In Slurm, `MAX_RUNTIME` is used as `SLURM_MAX_RUNTIME_OPTION` and passed to the driver as `driver->max_runtime`. This is then passed to the job script as `#SBATCH --time`. 

Questions (mostly for myself):

- What's the difference between `TIMEOUT` and `MAX_RUNTIME`?
- Do we just need to set `TIMEOUT` instead of `MAX_RUNTIME`?
- How is either `TIMEOUT` or `MAX_RUNTIME` implemented in the LSF queue? Are we using `LSF_BJOBS_TIMEOUT` instead? How is this passed to the job-submitting code?
- There seems to be no timeout option in the `LOCAL` queue.
- `TIMEOUT` seems not to be picked up in Slurm's options, is that right?
- `MAX_RUNTIME` is not picked up in the Torque driver. Should it be?

**Comment by kwinkunks** [comment]
@kvashchuka and I made some good progress on this today and are ready to write tests on Monday 🚀

**Comment by berland** [comment]
> * How is either `TIMEOUT` or `MAX_RUNTIME` implemented in the LSF queue?

You should not find an equivalent of `TIMEOUT` in LSF, as it is an ad-hoc measure taken for the flaky Azure PBS cluster only.
(LSF has its own pecularities where the `qstat` equivalent `bjobs` has to ssh into `$ERT_LSF_SERVER` to get its data, and similarly for `bsub`)

**Comment by kvashchuka** [comment]
Further actions:

- [ ] evaluate how much work it is to refactor the code such that global MAX_RUNTIME is passed to all queues 
- [ ] other option is to set it as queue option, but if we choose this route, we need also to test how it works when both global MAX_RUNTIME and queue option MAX_RUNTIME are set
- [ ] evaluate how much it will impact users if we discontinue queue option MAX_RUNTIME (currently used in SLURM)

**Comment by berland** [comment]
It turns out that MAX_RUNTIME is supported already. `job_queue_node.py` initiates killing the job, and this trickles down to `torque_driver_kill_job()` in `torque_driver.cpp`. Confirmed to work as intended.

**Comment by berland** [comment]
Robustness towards a flaky qdel command should be added to the resolution of this issue.
