### ISSUE TITLE
Investigate HPC Containers

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#518]
In the future we probably want to deploy the forward model environment in a container. Docker is currently not an option due to security issues and is hence often not fit for the task when it comes to a shared HPC cluster. There are numerous different efforts to address this and the homepage of _Slurm_ lists quite a few alternatives: https://slurm.schedmd.com/containers.html. There might be other options we should also consider.

A POC should provide a single executable that will run your forward model inside the container (this is sufficient to test it with current ERT via the `JOB_DISPATCH` key). The container could for instance be built either based on the script paths in `jobs.json` or by accepting a list of scripts (that would be extracted from a yaml-config). You can assume for now that all scripts are self-contained binaries.

Later, we will have to support installing python modules as well. Recommendations regarding this should also be provided. Last, distribution of the containers should also be discussed.

**Comment by jondequinor** [comment]
We used `udocker` which (may) depend on RHEL7, and `python2`.

Getting this to run in the `poly_case`.
`poly.ert`
```
JOB_SCRIPT job_dispatch_containerized
```

`job_dispatch_containerized`:
```sh
#!/bin/bash
udocker run --hostenv -v $1:/runpath \
-v /private/jond/libres/bin:/usr/local/bin \
-v /private/jond/containergroup/install/lib/python2.7/site-packages/job_runner:/usr/lib/python2.7/site-packages/job_runner \
-v /private/jond/ert/test-data/local/poly_example:/private/jond/ert/test-data/local/poly_example \
 job_runner1 job_dispatch.py /runpath
```

Where `job_runner1` is a pre-built container from the image `alpine:3.9` where some dependencies are _mounted_\* in.

We sat up `job_runner1` like this:
```sh
apk --update add python
apk add py-pip
apk add py-psutil
pip install future
pip install requests
```

We also disabled the `networking` reported in `job_runner.reporting` since it depends on `libecl`.

\* Not mounted, but probably copied over. This is a `udocker` limitation.

**Comment by jondequinor** [comment]
This was investigated, see above comment.
