### ISSUE TITLE
Double memory usage when opening ert with GRID keyword

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#5217]
**Describe the bug**
Because an EclGrid is opened in `ensemble_config` and we compare configurations from different parsing of the configuration, we have very high memory usage at startup in cases with GRID as we have to instances of the same grid opened twice.

**Comment by oysteoh** [comment]
@eivindjahren  can you update and close?

**Comment by eivindjahren** [comment]
This should not be a blocker for the release as there is no more memory used than before (we already allocated it twice and the new allocation is freed before we allocate again according to my tests). This will ultimately be fixed by overall reducing the amount of memory used for reading grid as we require very little of the data that is in the file.
