### ISSUE TITLE
User story: investigate result of each job in the forward model

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#529]
**I need to**
Carefully examine how each part/job of a forward_model is executed. If multiple jobs change the same file, I need to verify that both jobs behave as intended. This is mainly performed in advance of a longer run in order to check the setup.

**So that**
I can verify that my configuration is properly setup and verify that what I wanted to do actually is the things that are done.

**Currently I**
Run my setup locally multiple times, each time adding the next job in the config file and at the same time investigate my runpath to check the output of each job. If I run the entire setup once (`single experiment`) I can't guarantee that the output from each job is as expected.

**Suggestion**
Have a play/pause mode, where each step would visualize which files were added/modified/deleted

**Comment by lars-petter-hauge** [comment]
I really don't know about the value of this function, if it would be really beneficial, just "nice to have", or if it in fact would over complicate and make it even more frustrating to use..

I just had an idea though, that one could use `git` in order to get most of this for free. Say you do a `git init` in the given realization/run-path, and for each job ran you would `git status` to check what has changed and `git add --all & git commit` before running the next job. Everything that has to do with file adding/modifying/deleting would be captured.

There are so many already implemented ways of visualizing git staging area that we could capitalize of.

And hey presto, you would get the ability of going back to the result of a former job (`git checkout`...) and restart from there.

Not clear about large binary files though.

**Comment by jondequinor** [comment]
I think we need to remove one of the drivers of this issue; namely that the state of the ERT simulation is ephemeral. Currently, if forward models _α_ and _β_ run, the state—as it was immediately after _α_—is lost. This could be changed if instead _α_ was just a transaction on some immutable state, that produced a new immutable state _α′_. _β_ would then be a transaction that produced _β'_ from _α'_  and so on.

Since _β'_ is immutable, the user can access this even after move-to-cloud. After all, it's just a bunch of read-only files. And it would be trivial to change _β_ and get a new _β⁗_, without having to worry about _α_ or _α'_.

**Comment by jondequinor** [comment]
Let's close this for now.

> […] If multiple jobs change the same file, I need to verify that both jobs behave as intended[…]
I think this is technically impossible in current ERT. It will be solveable using the new input/output guarantees by the new Ensemble Evaluator.
