### ISSUE TITLE
Change default ES-MDA weights to (1 / number of iterations) and remove from GUI

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#5636]
The current default weights are "4, 2, 1".
According to [emerick2013](https://www.researchgate.net/publication/256938201_Ensemble_Smoother_with_Multiple_Data_Assimilation) on which the implementation is based, there is probably nothing to gain from this.

From emerick2013:
"Selecting the coefficients ai’s in a decreasing order resulted in further reduction in the values of ON, although the differences are not significant."

In the name of simplification, I suggest we set the weights to (1/number of iterations) and remove the possibility to set them from the GUI. Our users should not have to worry themselves about such details I think.

**Comment by Blunde1** [comment]
Hard to say for me if a simplification if good since I do not understand the details of ES-MDA. Maybe someone else that is informed have opinions.

In general though, I am in the corner of exposing the full assimilation algorithm, its hyperparameters, and the results to the users, while hopefully having good defaults. I hope that users will take informed decisions on tuning. If they do not want this, then we should try to provide as good adaptiveness of the algorithm to the specific problem as possible. This usually requires some thinking.

I have Emerick 2013 on my reading list, but it will not be this week. I can join in on the discussion of this afterwards.

**Comment by dafeda** [comment]
I am for exposing everything via config files but not necessarily via the GUI.
Also, I currently don't see any reason to tune this parameter.
I know @geirev has done some thinking here, so we should have a chat with him.

**Comment by geirev** [comment]
Some papers tried or proposed to optimize the weights, and I also looked at this problem in my 2018 paper.
My conclusion is that there may be a marginal improvement from using weights that decrease as a geometric series like the current default in ERT. I use ESMDA a lot in different applications and always set the weights equal to 1/(n_mda), where n_mda is the number of steps. 

In ESMDA, it is much more critical how many steps we use. We define convergence as the number of steps needed until a further increase of steps doesn't change the results further (within a given tolerance).

**Comment by dafeda** [comment]
Thank you Geir.
The default of 4, 2, 1 is used in many current experiments so it's not straight forward to change it as it will effect results.
We could perhaps change the default to 1/(n_mda), remove it from the GUI and notify users that they need to set the weights manually in the config if they wish to reproduce results.

**Comment by dafeda** [comment]
Closing this as stale and not a priority.
The fact that it changes default behaviour makes it quite difficult to do.
