### ISSUE TITLE
Run OPM as a forward model

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#573]
There was some issues with binary overloading in PATH in the current stable version, but external users have also reported problems with running flow in fresher builds. Setup a simple setup like SPE1 (see https://github.com/OPM/opm-tests/tree/master/spe1) and run it via ERT.

**Comment by wouterjdb** [comment]
I hope that this is the right issue, but some clarification to what I said to @markusdregi:

What I observed was that OPM flow could not find all of it's dependencies when started by ERT. Just running Flow directly from the same terminal worked fine.

The problem that I encountered was that in some of the newer versions of ERT the execution of external software by ERT has been changed from `os.execute` (or something along those lines) to the `subprocess `package. When starting software via the subprocess call you can specify an environment, which is what comes from some configuration yml file. I did not specify any alternative environment because I just want to run with the environment that ert is started from. However, and empty dictionary `{}` is what will be passed to the subprocess call instead of `None` (a `None` would be interpreted as 'use the parents environment).

I can get things to run again when I add the `env` option to the yml file:

```
env:
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH
```

And then it OPM Flow runs fine....

**Comment by mortalisk** [comment]
How did you set up the configuration?

**Comment by wouterjdb** [comment]
Which configuration are you thinking of specifically?

**Comment by mortalisk** [comment]
I was thinking of how the job is specified. However, I just learned from Markus that a flow job already exists, so I guess you simply use that.

**Comment by wouterjdb** [comment]
The only thing I create is the flow_config.yml file: 

```
cat >`ls -d $INSTALL_ENV/lib/python3*/$PACKAGE_FOLDER/res/fm/ecl`/flow_config.yml <<EOL
versions:
  '2019.04':
    scalar:
      executable: $FLOW_PATH
EOL
```

**Comment by mortalisk** [comment]
You are running a local build? What is your .ert config file?

**Comment by wouterjdb** [comment]
```
NUM_REALIZATIONS 10
MIN_REALIZATIONS 40%
MAX_RUNTIME 10
STOP_LONG_RUNNING TRUE
ITER_COUNT 10

--QUEUE_SYSTEM LOCAL
--QUEUE_OPTION LOCAL MAX_RUNNING 1

--Use the LSF cluster to run simulations
QUEUE_SYSTEM LSF
LSF_SERVER st-grid01
QUEUE_OPTION LSF LSF_QUEUE mr
QUEUE_OPTION LSF MAX_RUNNING 200
```

and then all of the jobs (3). Do you need anything specific?

**Comment by mortalisk** [comment]
How does the flow job line look like?

**Comment by wouterjdb** [comment]
`SIMULATION_JOB FLOW <ECLBASE> "--version=2019.04"`
