### ISSUE TITLE
Discuss Eclipse version passing system

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#614]
There are at least three ways to specify Eclipse version, some slightly broken, we need to make a plan.

**Comment by jondequinor** [comment]
Could someone with better insight into this expand?

- What are the three methods?
- For what reasons were the three methods created?
- What constraints are there in relation to Eclipse versioning/deployment?
- Should versions vary between FMs? If not, why not a single configuration option? If it does, why in the name of dog?

**Comment by markusdregi** [comment]
Could you start by listing the three alternatives? :)

**Comment by sondreso** [comment]
See also: #654

**Comment by markusdregi** [comment]
Alright, I can give it a go. As far as I can tell the three ways of specifying your eclipse version is:
- In the forward model name (`ECLIPSE100_2015.2`)
- As an argument to the forward model classical style (`ECLIPSE100(...., <VERSION>=2015.2)`)
- As an argument to the forward model Everest/shell style (`eclipse100 .... --version=2015.2`)

The first two are definitively to disappear. The first one the fastest, because this one should not survive to Python 3. The second one will live as long as the classic ERT configuration does. The last one will be part of the discussion of how we are to pass arguments in a yaml-based configuration file. It could either be the shell style, or perhaps we will allow multiple "forward model languages", where the third option could be one of the alternatives.

As for reasons I can only comment on the later two, where the second was to avoid the forward model generation in ERT-Statoil and the third was to facilitate a more transparent abstraction layer between the forward model configuration and what is actually happening.

It definitively varies between different configurations. Some asset might have a model that runs with Eclipse100 2015.2 and another a model that runs with Eclipse100 2018.7. So it will have to be configurable on the config-level. Whether there exists setups where they use one version of Eclipse in one part of the forward model and another later in the forward model I don't know. Maybe @eivindsm, @lars-petter-hauge or @oyvindeide can comment on whether this would ever make sense? On the other side, do we really want to drag simulator version out of the forward model job configuration and into the global scope of the configuration?
