### ISSUE TITLE
Investigate releasing the Global Interpreter Lock with pybind

### ISSUE THREAD

**Issue by andreas-el** [equinor/ert#6199]
Look into how we can release the GIL when using pybind

This has caused ERT to become quite unresponsive due to the GIL being held when calling pybind functions.

Ref.
https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil

**Comment by pinkwah** [comment]
You should just easily be able to do it like so using RAII (~ context manager in Python):
https://github.com/equinor/ert/blob/b577c65de9e927532f77a65ea174c777b1cd0d40/src/clib/lib/block_fs_native/module.cpp#L171

Add this line where needed. Note when unlocking the GIL you should never create Python objects. If you want to populate a numpy array, create it first, obtain a pointer to its contents, lock the GIL and then do your thing.

Should be really easy to do.

**Comment by andreas-el** [comment]
> You should just easily be able to do it like so using RAII (~ context manager in Python):
> 
> https://github.com/equinor/ert/blob/b577c65de9e927532f77a65ea174c777b1cd0d40/src/clib/lib/block_fs_native/module.cpp#L171
> 
> Add this line where needed. Note when unlocking the GIL you should never create Python objects. If you want to populate a numpy array, create it first, obtain a pointer to its contents, lock the GIL and then do your thing.
> 
> Should be really easy to do.

Sure, and it seems to work as intended too.
I'm just concerned that we are messing up wrt threads, data races etc in general.
So trying to go slow to get it right.

**Comment by pinkwah** [comment]
The quality and thread-safety of code is beyond the scope of the issue and CWrap does not do anything to handle it.

The only real difference is that CWrap is built on ctypes.CDLL[^1], while pybind11 is a native C extension. The difference is that CDLL doesn't have access to Python, and can therefore be assumed to not interfere with anything that uses GIL, so it's unlocked. Because pybind11 functions may create Python objects, the default for pybind11 is to have the GIL locked.

As for the quality of the underlying code, there is no difference with either method. If the code was broken with cwrap, it will still be as broken with pybind11 and that's okay.

[^1]: https://docs.python.org/3/library/ctypes.html#ctypes.CDLL
