### ISSUE TITLE
Warn if forward init will not be respected in iter 0

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#632]
Give the users a warning if `FORWARD_INIT` is active for a parameter, `iter` is set to 0 and there is data in storage for that very parameter when starting a run. The warning should say something along the lines of:

```Warning: Forward initialisation will not be done for {parameter} due to the case already containing values. For resampling from forward model you need to delete case: {case_name}.```

with options `continue` and `cancel`.

**Comment by oyvindeide** [comment]
I agree with the intention here, but think we might want to do this on the run model level instead? We have started that process, so you will now only sample the prior if it is iteration 0. We should make the  `storage` creation even more explicit, so that if we call: `EnKFMain.sample_prior` it is always overwritten. That means adding a `verify` function to the `BaseRunModel` or something like that.

**Comment by oyvindeide** [comment]
related to: #4224

**Comment by oyvindeide** [comment]
I will close this as it is not really that actionable.
