### ISSUE TITLE
Move RETRY driver (submit & kill) functionality into the Scheduler

### ISSUE THREAD

**Issue by xjules** [equinor/ert#6708]
Retry functionality should be handled commonly regardless the driver in use and thus it should be moved to Scheduler.

**Comment by berland** [comment]
I think I would like to argue that any flakyness in the LSF system is a private matter for the LSF driver, thus it should be handled in the driver. 

The drivers could though share their band-aid code for working around their respective flakyness situations they should handle.

**Comment by xjules** [comment]
> I think I would like to argue that any flakyness in the LSF system is a private matter for the LSF driver, thus it should be handled in the driver.
> 
> The drivers could though share their band-aid code for working around their respective flakyness situations they should handle.

I would argue that since the retry functionality is a linked to a single realization (going from EXIT to SUBMITTED) and as such it should be part of either RealizationState / Scheduler.

**Comment by jonathan-eq** [comment]
Putting this back to Todo for further discussion

**Comment by berland** [comment]
Hmm, are we mixing again the two different retry concepts:

* The retry in the driver in case bsub/qsub fails due to any flakyness in LSF/Torque
* The retry in the scheduler when any of the forward models fail, limited by MAX_SUBMIT

I would argue that the first retry belongs in the driver, and the second retry functionality in the scheduler.

**Comment by xjules** [comment]
As this was fixed in a feature toggled scheduler, closing this one.
