### ISSUE TITLE
"Everything" is smaller in python 3 on rgs

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#674]
Fonts, icons and window is smaller in python 3 on rgs node

![image](https://user-images.githubusercontent.com/3437958/74027523-9c124d80-49a8-11ea-966c-7a705309aaca.png)

**Comment by sondreso** [comment]
Only noticeable difference is `$ ert gui poly.ert 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-sonso'` in py3

**Comment by dotfloat** [comment]
Qt4 and Qt5 do styling wildly differently and so it's not viable for us to try to replicate how the Qt4 version looks. They're very different on my RHEL7 machine also.

On GNOME, both will try to replicate the current theme, with Qt4 using GTK+2 theme (Clearlooks usually) while Qt5 should use the GTK3 theme (Adwaita by default). Neither the `PyQt5` package, nor the version in komodo has the necessary plugin to emulate GTK3 themes (QGnomePlatform), while our RHEL7 installs do.

Anyway, I think it's more viable to redesign the interface rather than trying to keep ERT's programmer UI.

I'll close this with a WONTFIX unless someone objects.
