### ISSUE TITLE
Check all divisions for expected integer result

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#676]
https://github.com/equinor/ert/issues/671 was caused by change in division behavior between python 2 and python 3. We should check that all divisions expecting an integer as result is actually explicitly converted to int. 

- [x] libecl
- [x] libres
- [x] ert

**Comment by jondequinor** [comment]
from https://github.com/equinor/libecl/blame/master/python/ecl/eclfile/ecl_kw.py#L550
```python
                if not mul:
                    factor = 1.0 / factor
                if self.data_type.is_int():
                    if isinstance(factor, int):
                        self._scale_int(factor)
                    else:
                        raise TypeError("Type mismatch")
```
@pgdr @markusdregi for both python 2 and 3 this is _true division_. I.e., it will always raise `TypeError` here. What was intended?

**Comment by jondequinor** [comment]
Other than that, `libecl` seems to not return floats where integers were expected. It does treat days as floats, but the behaviour is the same for both py2 and py3.

**Comment by markusdregi** [comment]
You are right and I think we should leave it as is. The code is not the easiest to argue about due to late exists etc, but in this case we are basically in the following scenario:
- we have an integer vector at hand,
- we are to divide all elements by some factor and return a new integer vector

This can of course work out in some very rare cases, but in most (if not all real) cases, this will not work and one should not expect it to work. Is the error message not very descriptive? Definitively! But so is the message for `non-numerical` types. We could improve the messages, but beyond that I think we should leave it as is ;)

**Comment by jondequinor** [comment]
ERT looks OK. It seems Qt accepts floats just fine for APIs like `QColor` etc.

Recommend specific bugs be created if needed.
