### ISSUE TITLE
Field saved as 64-bit float after update

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6846]
A user reported that the output fields were twice the size of the input grids, indicating that the field goes from 32 - 64-bit. Was using `roff` fiields. Using komodo 2023.11.04

**Comment by kvashchuka** [comment]
Steps to reproduce:
1. log in to RGS node and source komodo stable (2023.11.06)
2. `cp /project/oompf/komodo_ci_testdata/poly-roff/* ert/test-data/poly_example/poly_out/realization-0/iter-0/`
4. `ert es_mda poly_roff.ert`
5. check size of `A_Perm.roff` in `poly_example/poly_out/realization-0/iter-2` for example (8000358 vs 16000334)

**Comment by eivindjahren** [comment]
It is possible to simply add a `astype(np.float32)` here:

https://github.com/equinor/ert/blob/fc7c5ba8550730a54b13d3b56373875a048d7f4b/src/ert/field_utils/roff_io.py#L42

I believe rms will not read the parameter if it is float64 rather than float32 so it not just an issue with
the file being too big, but it also means rms fails to read the field.

However, we have previously enforced float32 everywhere for memory reasons so this solution may mask other
problems.
