### ISSUE TITLE
Create end-point for calculating std. dev. for all parameter types

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#6996]
Need to implement an endpoint in storage for calculating variance of parameters. Because we have the potential for large fields, we should use Welfords algorithm :https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford%27s_online_algorithm

**Comment by Blunde1** [comment]
Do you intend to compute variance over a field, as if it was one parameter? Welfords algorithm is intended for independent samples. Elements in fields are highly correlated. So the goal of Welford and the algorithm itself is not suitable. For scalar variables we have small ensemble sizes, so I do not think we will have problems with numerics.

If you seek to measure "variance" for a multivariate distribution, and have one number for the prior and one for the posterior, then likely you seek $\text{det}(\text{cov}(X,X))$. 

See e.g. https://en.wikipedia.org/wiki/Generalized_variance

To compute this from few high dimensional samples requires some clear thinking. In particular, one cannot substitute $\text{cov}(X,X)$ with the sample covariance matrix for statistical reasons, even if one could compute it.

**Comment by dafeda** [comment]
We would I think like to plot the variance of a field-ensemble so that we can gauge the "strength" of the update.
You may remember Evensen using such plots to compare updates with and without adaptive localization.
I would include them here, but don't think the figures are open-source.
Does this make sense @Blunde1 ?

**Comment by Blunde1** [comment]
I do not remember what Evensen has shown, but perhaps it is like the plot below? In this case one computes on individual elements of the sampels of the elements in field-vectors. So calculations are separate from the size of the field. What matters is the number of samples. Ensemble size is not large. So Welford's algorithm is not needed, I think. `np.std()` on the vectorized field should do the trick. See e.g. this notebook: https://github.com/equinor/graphite-maps/blob/main/docs/source/GaussianField.ipynb

This is okay for visualizations of the strength of the update on individual scalar parameters. But plotted according to their position.

The strength of the update is related to the volume of the data cloud of the ensemble. This is measured by $\text{det}(\text{cov}(X,X))$, and provides one number for the overall strength of the update. A visual proxy for this is e.g. the plots below. They are easily computed, even with many parameters.

![image](https://github.com/equinor/ert/assets/13650516/90d25c20-a822-4298-b7fe-819139291e13)

**Comment by dafeda** [comment]
Yes, those plots are similar to what Evensen used.
Just to make sure that I understand your example, is `U_posterior` of dimension (num_params_x, num_params_y, num_realizations)?
The reasoning behind wanting to use Welford's algorithm is that it makes it possible to calculate the variance without holding the whole ensemble in memory.
However, we have done a lot since then to reduce memory usage, so `np.std` may well work just fine.

**Comment by Blunde1** [comment]
`U` and `U_posterior` are of shape `(num_realizations, num_params_total)` where `num_params_total= num_params_x* num_params_y`. They are the prior and posterior ensembles of vectorized fields. I think ERT's implementation of update algorithms uses the transpose of this.

To do the calculations for a point, only the samples for that scalar is needed. So, if memory is a problem, then one would load all samples of as many parameters as possible and calculate `np.std` over this batch, store the calculations and then take a new batch of parameters with the same calculations, etc.

**Comment by dafeda** [comment]
Ah, now I remember why we considered Welfords. It was not necessarily due to memory considerations.
Instead, we wondered whether we could calculate the variance on the fly.
That is, once a realization was completed, we could use Welfords algorithm to update the variance without having to recalculate from scratch.
Might perhaps be useful sometime in the future, but not now I think.
