### ISSUE TITLE
Find all deprecation warnings in our codebase today

### ISSUE THREAD

**Issue by oysteoh** [equinor/ert#737]
Find all deprecation warnings in the codebase used today. We need to actually do something about them. Categorize by criticality - which then again will decide if we remove immediately or if we need to make additional measures first. Create issues for all warnings found in this milestone which will make it possible for us to track those

**Comment by markusdregi** [comment]
Should the issues also be put into this milestone perhaps?

**Comment by oysteoh** [comment]
> Should the issues also be put into this milestone perhaps?

just did - changed the text to instruct the developer to create issues in this milestone

**Comment by mortalisk** [comment]
Found these mentions of deprecations in ert repo:

- docs/rst/latex/titlesec.sty
  - line 927, 1033 has some deprecated somethings, are these latex styles in use somewhere?
- rst/manual/reference/queue.rst  (1 usage found)
  - line 15 claims queue system RSH is deprecated since a half year ago, remove this system?
- docs/rst/manual/reference/configuration/keywords.rst
  - this file lists a lot of deprecated keywords. Remember to go through this and update after we have removed all deprecated keywords (probably mostly defined in libres)

**Comment by jondequinor** [comment]
> line 15 claims queue system RSH is deprecated since a half year ago, remove this system?

No, users has found it to be useful, so it will stay. See 

- https://github.com/equinor/ert/issues/930
- https://github.com/equinor/ert/issues/931

**Comment by mortalisk** [comment]
Created issues https://github.com/equinor/libres/issues/961 and https://github.com/equinor/libecl/issues/717 listing all deprecations in libres and libecl.

**Comment by markusdregi** [comment]
Deprecation warnings have been found, as the issue requested. I'm closing this one,
