### ISSUE TITLE
Typo in "Configuration summary": Should be "Forward models" and not "Forward model"

### ISSUE THREAD

**Issue by dafeda** [equinor/ert#7911]
**Describe the bug**

**To reproduce**
Steps to reproduce the behaviour:
1. `pip install ert`
2. Create `config.ert` with a single line: `NUM_REALIZATIONS 5`
3. `ert gui config.ert`

![image](https://github.com/equinor/ert/assets/45088507/a2d8165b-d463-4312-91d9-c24e4f57de20)

**Expected behaviour**

Instead of "Forward model (0 step)", I expect "Forward models (0 step)" because we have "Parameters (0)" and "Observations (0)".

**Comment by berland** [comment]
The current choice of singular form is by intention. At some point we might want to face the reality that the sum of all keywords "FORWARD_MODEL" in the config is _The Forwardmodel_, and not multiple forward models. The term "step" is introduced here to match 1-1 with each FORWARD_MODEL keyword in the config (since the Ert3 step concept is long gone, we have chosen to reuse it) since we in the code call it ForwardModelSteps.

**Comment by berland** [comment]
But I see another typo in the screenshot, it should state "0 step**s**"

**Comment by dafeda** [comment]
> The current choice of singular form is by intention. At some point we might want to face the reality that the sum of all keywords "FORWARD_MODEL" in the config is _The Forwardmodel_, and not multiple forward models. The term "step" is introduced here to match 1-1 with each FORWARD_MODEL keyword in the config (since the Ert3 step concept is long gone, we have chosen to reuse it) since we in the code call it ForwardModelSteps.

Thanks 👍
