### ISSUE TITLE
Use gunicorn as flask wsgi server if --production

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#807]
The flask dev server is most likely single threaded, in any case slow.

We should get used to running some other server if in _production_, this could be gunicorn.

So if `ert api --production` a gunicorn server should host the flask app.

**Comment by ManInFez** [comment]
Also include spawning the flask server at startup of ERT

**Comment by anders-kiaer** [comment]
Mentioned internally on Slack, but mentioning it here as well (since everything easily disappears over time in a channel):

Maybe [`fastapi`](https://github.com/tiangolo/fastapi) also could be something to consider (if not already) in order to increase performance of the API server. There are also some docs regarding [`SQL + fastapi`](https://github.com/tiangolo/fastapi/blob/07e094fd5077e12150099390eb4ed2d8532db707/docs/en/docs/tutorial/sql-databases.md#sql-relational-databases) available.
