### ISSUE TITLE
Deprecate Slurm queue option MEMORY_PER_CPU

### ISSUE THREAD

**Issue by berland** [equinor/ert#8199]
This slurm option does not go hand-in-hand with the unification of memory handling in Ert that is supposed to happen in #7798 , and is therefore suggested to be deprecated.

Adding deprecation messages to the config parsing is sufficient, stating that is feature is slated for removal. 

(The other Slurm option MEMORY will have its functionality kept, but will transition into a global Ert keyword)

**Comment by berland** [comment]
Maybe @verveerpj knows if this option is in use and should perhaps be kept as is?

**Comment by verveerpj** [comment]
Everest supports the `--mem` and =`--mem-per-cpu` options via the current SLURM driver, which I guess map on `MEMORY` and `MEMORY_PER_CPU`. We have used the latter, but I think in that particular case we could also just have used the first.

However, Everest has a `cores_per_node` for the number of CPU`s a forward model may use, I think that maps onto `NUM_CPU`? Is ERT going to retain that, and if so, is it going to retain an option to specify the memory per cpu? Or is that considered not to be necessary?

In any case, for now Everest can just follow whatever is appropriate for ERT, since the use case is probably going to be very similar.
