### ISSUE TITLE
Expose environment variables with run information in compute nodes

### ISSUE THREAD

**Issue by tnatt** [equinor/ert#8515]
**Is your feature request related to a problem? Please describe.**
The environment variables 

- _ERT_EXPERIMENT_ID 
- _ERT_REALIZATION_ID
- _ERT_SIMULATION_MODE

are not available from the compute nodes. 

**Describe the solution you'd like**
I would like the run information to be available also from `FORWARD_MODELS` running on the compute node (now it is only available for `FORWARD_MODELS` during `ERT test-run`'s).

**Additional context**
Feature introduced in #4904
https://github.com/equinor/fmu-dataio/issues/605

**Comment by sondreso** [comment]
PR where this was introduced originally: https://github.com/equinor/ert/pull/5127/files

**Comment by sondreso** [comment]
Which version of ERT did you test this with? :slightly_smiling_face:

**Comment by tnatt** [comment]
> Which version of ERT did you test this with? 🙂

I did a test in bleeding today before writing the issue (at least I think I did 😄)..

**Comment by DanSava** [comment]
The environment variables
```
_ERT_EXPERIMENT_ID
_ERT_ENSEMBLE_ID
_ERT_SIMULATION_MODE
```

They were not designed to be available on the compute node. The feature request https://github.com/equinor/ert/issues/4904 mentioned they should be available on the client. This matches with

>  it is only available for FORWARD_MODELS during ERT test-run's.

this is because when running the command `ert test_run config_file.ert`  the forward model job will run on the client machine.
