### ISSUE TITLE
ECLBASE is just using basename in runpath file

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#8522]
### What happened? (You can include a screenshot if it helps explain)

Previously the full ECLBASE was used in the runpath file when JOBNAME was not configured, however in https://github.com/equinor/ert/pull/7350 that was changed to just basename. That means workflows parsing the runpath file to access simulation files are no longer looking in the right place.

### What did you expect to happen?

Full ECLBASE in runpath file.

### Environment where bug has been observed

- [X] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [X] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by eivindjahren** [comment]
As far as I know, the problem is that `CSV_EXPORT2` expects `ECLBASE` to be the 3rd argument on each line of the runpath_list file. However, what has been put there is the jobname which has often been the eclbase. However, there were never any guarantee that jobname was the same as eclbase, and furthermore, on OpenPBS, "/" is not a valid character in a jobs name.

We could probably solve this by putting eclbase in the runpath_list if it exists, otherwise we put jobname.
