### ISSUE TITLE
Project code not reported correct

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#8575]
### What happened? (You can include a screenshot if it helps explain)

The feature added [here](https://github.com/equinor/ert/pull/8175) does not seem to function as intended: 

![image](https://github.com/user-attachments/assets/6406c83d-58f6-44ac-97f2-63799a0faca4)

Red shows komodo deprecated (2024.06) 
Green shows komodo stable (2024.08)
Blue shows komodo bleeding (from August 26th)

### What did you expect to happen?

Project code should not be username, but rather include the pre-configured jobs if they are used. 

### steps to reproduce

- Modify the name of the forward model job in the poly example to be named after either of the pre-configured job names that should show up in the project code. 
- Switch to LSF and run ensemble experiment.
- Watch the output of `bjobs -l -a | grep "Project"`

### Environment where bug has been observed

- [X] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [X] rhel7
- [ ] rhel8
- [ ] local queue
- [X] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
- [ ] used flag `--enable-scheduler`

**Comment by DanSava** [comment]
The logic is set such that ERT will add a default `PROJECT_CODE` `QUEUE_OPTION` if there is a simulator (FLOW, ECLIPSE or RMS) in the FORWARD_MODEL list. 

If there is already a `QUEUE_OPTION LSF PROJECT_CODE user:$USER` defined ERT will not replace this user-defined option with the simulator tag. This is what is causing what was observed in the issue description due to [this](https://github.com/equinor/ert-configurations/blob/d79bd00a42e2a673a6a718d1fa989d353c9a0e55/ert_configurations/site_config.py#L22) in `ert-configuration`

Removing that line from ert-configurations. will lead to the expected behaviour:
![image](https://github.com/user-attachments/assets/8bf889b1-a33b-4b7c-811b-27c52d034447)

**Comment by DanSava** [comment]
Until we decided to add the simulated tag under the `PROJECT_CODE` option this option value was never used. I suggest just removing it form the default list in `ert-configurations`. https://github.com/equinor/ert-configurations/pull/119

**Comment by DanSava** [comment]
Should be fixed by https://github.com/equinor/komodo-releases/pull/6172

**Comment by sondreso** [comment]
Fix is now deployed
