### ISSUE TITLE
Simplify everest server launching

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/ert#8905]
Everest server currently starts an entire ERT instance only to run itself as a forward model. We do need to submit the everserver to the queue, but how we do it is up to us. One way of doing this could be to do a BaseRunModel, but BaseRunModel might make more sense for the actual batch simulation / optimization part.

(Original text: Create a BaseRunModel for the everest server.)

**Comment by yngve-sk** [comment]
I think we could maybe create a minimal setup (TLDR; create a queue driver, submit a job_dispatch.py via it, and have a jobs.json generated from the everserver ert config in the cwd which is the "everest runpath") that will submit the forward model to the queue so that it runs. I'm not sure if we need any monitoring beyond that, as the server itself exposes monitoring endpoints accessible via http requests AFAIK

**Comment by oyvindeide** [comment]
Blocked by: https://github.com/equinor/ert/issues/9002
